#region Using declarations
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Input;
using System.Windows.Media;
using System.Xml.Serialization;
using NinjaTrader.Cbi;
using NinjaTrader.Gui;
using NinjaTrader.Gui.Chart;
using NinjaTrader.Gui.SuperDom;
using NinjaTrader.Gui.Tools;
using NinjaTrader.Data;
using NinjaTrader.NinjaScript;
using NinjaTrader.Core.FloatingPoint;
using NinjaTrader.NinjaScript.DrawingTools;
using DMFX.DarkMindConnect;
using DMFX.Interfaces;
using DMFX.QuotesInterfaces;
#endregion

//This namespace holds Indicators in this folder and is required. Do not change it. 
namespace NinjaTrader.NinjaScript.Indicators
{
	public class DMFXCOTCmdtsFut : Indicator
	{
		public enum ECOTCmdtsCodes
		{
			WHEAT_SRW___CHICAGO_BOARD_OF_TRADE_	 = 0	,
			BLACK_SEA_WHEAT_FINANCIAL___CHICAGO_BOARD_OF_TRADE_	 = 1	,
			WHEAT_HRW___CHICAGO_BOARD_OF_TRADE_	 = 2	,
			WHEAT_HRSpring___MINNEAPOLIS_GRAIN_EXCHANGE_	 = 3	,
			CORN___CHICAGO_BOARD_OF_TRADE_	 = 4	,
			OATS___CHICAGO_BOARD_OF_TRADE_	 = 5	,
			SOYBEANS___CHICAGO_BOARD_OF_TRADE_	 = 6	,
			CALIF_CARBON_ALL_VINTAGE_2018___ICE_FUTURES_ENERGY_DIV_	 = 7	,
			NJ_SRECS_VINTAGE_2019___ICE_FUTURES_ENERGY_DIV_	 = 8	,
			NJ_SRECS_VINTAGE_2020___ICE_FUTURES_ENERGY_DIV_	 = 9	,
			PJM_TRI_RECs_CLASS_1_Vin_2019___ICE_FUTURES_ENERGY_DIV_	 = 10	,
			MASS_RECs_CLASS_1_Vin_2018___ICE_FUTURES_ENERGY_DIV_	 = 11	,
			PJM_TRI_RECs_CLASS_1_Vin_2020___ICE_FUTURES_ENERGY_DIV_	 = 12	,
			MASS_RECs_CLASS_1_Vin_2019___ICE_FUTURES_ENERGY_DIV_	 = 13	,
			CALIF_CARBON_ALL_VINTAGE_2019___ICE_FUTURES_ENERGY_DIV_	 = 14	,
			PJM_TRI_RECs_CLASS_1_Vin_2021___ICE_FUTURES_ENERGY_DIV_	 = 15	,
			NJ_SRECS_VINTAGE_2021___ICE_FUTURES_ENERGY_DIV_	 = 16	,
			NJ_SRECS_VINTAGE_2022___ICE_FUTURES_ENERGY_DIV_	 = 17	,
			MASS_RECs_CLASS_1_Vin_2020___ICE_FUTURES_ENERGY_DIV_	 = 18	,
			CALIF_CARBON_VINTAGE_2020___ICE_FUTURES_ENERGY_DIV_	 = 19	,
			NJ_SRECS___ICE_FUTURES_ENERGY_DIV_	 = 20	,
			RGGI_VINTAGE_2018___ICE_FUTURES_ENERGY_DIV_	 = 21	,
			PJM_TRI_RECs_CLASS_1____ICE_FUTURES_ENERGY_DIV_	 = 22	,
			CALIF_CARBON_VINTAGE_2021___ICE_FUTURES_ENERGY_DIV_	 = 23	,
			RGGI_VINTAGE_2019___ICE_FUTURES_ENERGY_DIV_	 = 24	,
			CALIF_CARBON_ALLOWANCE_V2022___ICE_FUTURES_ENERGY_DIV_	 = 25	,
			CT_RECs_CLASS_1____ICE_FUTURES_ENERGY_DIV_	 = 26	,
			MASS_COMPLIANCE_RECs_CLASS_1____ICE_FUTURES_ENERGY_DIV_	 = 27	,
			MARYLAND_SOLAR_REC___ICE_FUTURES_ENERGY_DIV_	 = 28	,
			MASS_SREC_CARVE_OUT_1___ICE_FUTURES_ENERGY_DIV_	 = 29	,
			SOYBEAN_OIL___CHICAGO_BOARD_OF_TRADE_	 = 30	,
			USGC_HSFO__PLATTS____ICE_FUTURES_ENERGY_DIV_	 = 31	,
			FUEL_OIL_3pct_USGC3_5pct_FOB_RDAM_BARGES___ICE_FUTURES_ENERGY_DIV_	 = 32	,
			USGC_HSFO_PLATTSBRENT_1ST_LN____ICE_FUTURES_ENERGY_DIV_	 = 33	,
			FUEL_OIL_NY_1pct__GULF_COAST_3pct___ICE_FUTURES_ENERGY_DIV_	 = 34	,
			GULF___6_FUEL_3_0pct_SULFUR___NEW_YORK_MERCANTILE_EXCHANGE_	 = 35	,
			EUR_3_5pct_FUEL_OIL_RTD_CAL___NEW_YORK_MERCANTILE_EXCHANGE_	 = 36	,
			SING_FUEL_OIL_380_cst_PLATTS___NEW_YORK_MERCANTILE_EXCHANGE_	 = 37	,
			MINI_EUR_3_5pctFOIL_RTD_CAL___NEW_YORK_MERCANTILE_EXCHANGE_	 = 38	,
			GULF_NO6_FO_3pct_v_EUR_3_5pct_RDAM___NEW_YORK_MERCANTILE_EXCHANGE_	 = 39	,
			MINI_SING_380_FUEL_OIL___NEW_YORK_MERCANTILE_EXCHANGE_	 = 40	,
			FUEL_OIL_380cst_SING3_5pct_RDAM___NEW_YORK_MERCANTILE_EXCHANGE_	 = 41	,
			_2_HEATING_OIL__NY_HARBOR_ULSD___NEW_YORK_MERCANTILE_EXCHANGE_	 = 42	,
			UP_DOWN_GC_ULSD_VS_HO_SPR___NEW_YORK_MERCANTILE_EXCHANGE_	 = 43	,
			NATURAL_GAS_HENRY_LD1_FIXED___ICE_FUTURES_ENERGY_DIV_	 = 44	,
			NATURAL_GAS_PENULTIMATE_ICE___ICE_FUTURES_ENERGY_DIV_	 = 45	,
			SOCAL_BORDER_FIN_BASIS___ICE_FUTURES_ENERGY_DIV_	 = 46	,
			PGE_CITYGATE_FIN_BASIS___ICE_FUTURES_ENERGY_DIV_	 = 47	,
			NWP_ROCKIES_FIN_BASIS___ICE_FUTURES_ENERGY_DIV_	 = 48	,
			AECO_FIN_BASIS___ICE_FUTURES_ENERGY_DIV_	 = 49	,
			CHICAGO_FIN_BASIS___ICE_FUTURES_ENERGY_DIV_	 = 50	,
			HSC_FIN_BASIS___ICE_FUTURES_ENERGY_DIV_	 = 51	,
			WAHA_FIN_BASIS___ICE_FUTURES_ENERGY_DIV_	 = 52	,
			ALGONQUIN_CITY_GATES_FINANCIAL_BASIS___ICE_FUTURES_ENERGY_DIV_	 = 53	,
			CHICAGO_CITYGATE__INDEX____ICE_FUTURES_ENERGY_DIV_	 = 54	,
			COLORADO_INTERSTATE___MAINLINE__BASIS____ICE_FUTURES_ENERGY_DIV_	 = 55	,
			COLUMBIA_GAS_CO____TCO_POOL__APPALACHIA___BASIS____ICE_FUTURES_ENERGY_DIV_	 = 56	,
			COLUMBIA_GULF_TRANSMISSION_CO_____MAINLINE_POOL___ICE_FUTURES_ENERGY_DIV_	 = 57	,
			DOMINION___SOUTH_POINT___ICE_FUTURES_ENERGY_DIV_	 = 58	,
			DOMINION___SOUTH_POINT__BASIS____ICE_FUTURES_ENERGY_DIV_	 = 59	,
			EL_PASO___PERMIAN_BASIN__BASIS____ICE_FUTURES_ENERGY_DIV_	 = 60	,
			EL_PASO___PERMIAN_BASIN__INDEX____ICE_FUTURES_ENERGY_DIV_	 = 61	,
			EL_PASO_SAN_JUAN_BASIN_BLANCO_POOL_PRIMARY_ONLY_BASIS___ICE_FUTURES_ENERGY_DIV_	 = 62	,
			HENRY_HUB___TAILGATE_LOUISIANA__BASIS____ICE_FUTURES_ENERGY_DIV_	 = 63	,
			HENRY_HUB___TAILGATE_LOUISIANA__INDEX____ICE_FUTURES_ENERGY_DIV_	 = 64	,
			HOUSTON_SHIP_CHANNEL__INDEX____ICE_FUTURES_ENERGY_DIV_	 = 65	,
			MICHCON_FINANCIAL_INDEX___ICE_FUTURES_ENERGY_DIV_	 = 66	,
			MICHIGAN_CONSOLIDATED_CITYGATE__GENERIC___BASIS____ICE_FUTURES_ENERGY_DIV_	 = 67	,
			NAT_GAS_LD1_for_GDD__TEXOK___ICE_FUTURES_ENERGY_DIV_	 = 68	,
			NATURAL_GAS_INDEX__ALGONQUIN_CITY_GATES___ICE_FUTURES_ENERGY_DIV_	 = 69	,
			NATURAL_GAS_PIPELINE_MID_CONTINENT_POOL_PIN__BASIS____ICE_FUTURES_ENERGY_DIV_	 = 70	,
			NATURAL_GAS_PIPELINE_TEXOK__BASIS____ICE_FUTURES_ENERGY_DIV_	 = 71	,
			NNG_VENTURA_FINANCIAL_INDEX___ICE_FUTURES_ENERGY_DIV_	 = 72	,
			NORTHERN_NATURAL_GAS___DEMARCATION_POOL__BASIS____ICE_FUTURES_ENERGY_DIV_	 = 73	,
			NORTHERN_NATURAL_GAS___VENTURA__BASIS____ICE_FUTURES_ENERGY_DIV_	 = 74	,
			NORTHWEST_PIPELINE___CANADIAN_BORDER__BASIS____ICE_FUTURES_ENERGY_DIV_	 = 75	,
			NORTHWEST_PIPELINE_CORP____ROCKY_MOUNTAINS___ICE_FUTURES_ENERGY_DIV_	 = 76	,
			PACIFIC_GAS_TRANSMISSION___MALIN__BASIS____ICE_FUTURES_ENERGY_DIV_	 = 77	,
			PANHANDLE_EASTERN__POOL_GAS__BASIS____ICE_FUTURES_ENERGY_DIV_	 = 78	,
			PANHANDLE_EASTERN__POOL_GAS__INDEX____ICE_FUTURES_ENERGY_DIV_	 = 79	,
			PGE___CITYGATE__INDEX____ICE_FUTURES_ENERGY_DIV_	 = 80	,
			SOCAL__INDEX____ICE_FUTURES_ENERGY_DIV_	 = 81	,
			SOCAL_CITYGATE_FINANCIAL_BASIS___ICE_FUTURES_ENERGY_DIV_	 = 82	,
			TEXAS_EASTERN__M3_ZONE__DELIVERED____ICE_FUTURES_ENERGY_DIV_	 = 83	,
			TEXAS_EASTERN__M3_ZONE__DELIVERED___BASIS____ICE_FUTURES_ENERGY_DIV_	 = 84	,
			TRANSCO_ZONE_6_BASIS___ICE_FUTURES_ENERGY_DIV_	 = 85	,
			TRANSCO_ZONE_6_MONTHLY_INDEX___ICE_FUTURES_ENERGY_DIV_	 = 86	,
			TRANSCONTINENTAL_GAS__STATION_85__ZONE_4____ICE_FUTURES_ENERGY_DIV_	 = 87	,
			TRANSCONTINENTAL_GAS___ZONE_6__NY___BASIS____ICE_FUTURES_ENERGY_DIV_	 = 88	,
			WAHA_HUB___WEST_TEXAS_DELIVEREDBUYERS_INDEX___ICE_FUTURES_ENERGY_DIV_	 = 89	,
			TETCO_M2_Basis__Receipts____ICE_FUTURES_ENERGY_DIV_	 = 90	,
			TRANSCO_LEIDY_BASIS___ICE_FUTURES_ENERGY_DIV_	 = 91	,
			REX_ZONE_3_BASIS___ICE_FUTURES_ENERGY_DIV_	 = 92	,
			REX_ZONE_3_INDEX___ICE_FUTURES_ENERGY_DIV_	 = 93	,
			NATURAL_GAS___NEW_YORK_MERCANTILE_EXCHANGE_	 = 94	,
			HENRY_HUB_LAST_DAY_FIN___NEW_YORK_MERCANTILE_EXCHANGE_	 = 95	,
			HENRY_HUB_PENULTIMATE_FIN___NEW_YORK_MERCANTILE_EXCHANGE_	 = 96	,
			HHUB_NAT_GAS_PENULT_FINL_10000___NASDAQ_FUTURES_	 = 97	,
			HHUB_NAT_GAS_PENULT_FINL_2500___NASDAQ_FUTURES_	 = 98	,
			COAL__API_2__CIF_ARA___NEW_YORK_MERCANTILE_EXCHANGE_	 = 99	,
			CBT_ETHANOL___CHICAGO_BOARD_OF_TRADE_	 = 100	,
			ETHANOL_T2_FOB_INCL_DUTY___NEW_YORK_MERCANTILE_EXCHANGE_	 = 101	,
			CHICAGO_ETHANOL___NEW_YORK_MERCANTILE_EXCHANGE_	 = 102	,
			SOYBEAN_MEAL___CHICAGO_BOARD_OF_TRADE_	 = 103	,
			EUROPEAN_NAPHTHA_CAL___NEW_YORK_MERCANTILE_EXCHANGE_	 = 104	,
			Mini_Eur_Naphtha_CIF_NEW___NEW_YORK_MERCANTILE_EXCHANGE_	 = 105	,
			COTTON_NO__2___ICE_FUTURES_U_S__	 = 106	,
			HENRY_HUB___NEW_YORK_MERCANTILE_EXCHANGE_	 = 107	,
			HENRY_HUB_PENULTIMATE_NAT_GAS___NEW_YORK_MERCANTILE_EXCHANGE_	 = 108	,
			MALAYSIAN_PALM_OIL_CALENDAR_SW___CHICAGO_MERCANTILE_EXCHANGE_	 = 109	,
			ROUGH_RICE___CHICAGO_BOARD_OF_TRADE_	 = 110	,
			FRZN_CONCENTRATED_ORANGE_JUICE___ICE_FUTURES_U_S__	 = 111	,
			BUTTER__CASH_SETTLED____CHICAGO_MERCANTILE_EXCHANGE_	 = 112	,
			MILK__Class_III___CHICAGO_MERCANTILE_EXCHANGE_	 = 113	,
			NON_FAT_DRY_MILK___CHICAGO_MERCANTILE_EXCHANGE_	 = 114	,
			CME_MILK_IV___CHICAGO_MERCANTILE_EXCHANGE_	 = 115	,
			DRY_WHEY___CHICAGO_MERCANTILE_EXCHANGE_	 = 116	,
			LEAN_HOGS___CHICAGO_MERCANTILE_EXCHANGE_	 = 117	,
			LIVE_CATTLE___CHICAGO_MERCANTILE_EXCHANGE_	 = 118	,
			RANDOM_LENGTH_LUMBER___CHICAGO_MERCANTILE_EXCHANGE_	 = 119	,
			FEEDER_CATTLE___CHICAGO_MERCANTILE_EXCHANGE_	 = 120	,
			CHEESE__CASH_SETTLED____CHICAGO_MERCANTILE_EXCHANGE_	 = 121	,
			PJM_WH_REAL_TIME_PEAK___ICE_FUTURES_ENERGY_DIV_	 = 122	,
			MID_C_DAY_AHEAD_PEAK___ICE_FUTURES_ENERGY_DIV_	 = 123	,
			MID_C_DAY_AHEAD_OFF_PEAK___ICE_FUTURES_ENERGY_DIV_	 = 124	,
			PJM_WESTERN_HUB_RT_OFF___ICE_FUTURES_ENERGY_DIV_	 = 125	,
			SP15_FIN_DA_PEAK_FIXED___ICE_FUTURES_ENERGY_DIV_	 = 126	,
			CAISO_SP15_FIN_DA_OFF_PEAK___ICE_FUTURES_ENERGY_DIV_	 = 127	,
			PJM_AEP_DAYTON_RT_OFF_PK___ICE_FUTURES_ENERGY_DIV_	 = 128	,
			PJM_AEP_DAYTON_RT_PEAK_FIXED___ICE_FUTURES_ENERGY_DIV_	 = 129	,
			PJM_AEP_DAYTON_HUB_DA_OFF_PK____ICE_FUTURES_ENERGY_DIV_	 = 130	,
			AD_HUB_DA_PEAK_DAILY___ICE_FUTURES_ENERGY_DIV_	 = 131	,
			PJM_AEP_DAYTON_DA_PEAK___ICE_FUTURES_ENERGY_DIV_	 = 132	,
			MISO_INDIANA__OFF_PEAK___ICE_FUTURES_ENERGY_DIV_	 = 133	,
			MISO_IN__REAL_TIME_OFF_PEAK___ICE_FUTURES_ENERGY_DIV_	 = 134	,
			ERCOT_HOUSTON_345KV_RT_PK_FIX___ICE_FUTURES_ENERGY_DIV_	 = 135	,
			ERCOT_NORTH_345KV_RT_PK_FIX___ICE_FUTURES_ENERGY_DIV_	 = 136	,
			ERCOT_NORTH_345KV_DA_PK_DLY_FI___ICE_FUTURES_ENERGY_DIV_	 = 137	,
			ERCOT___NORTH_MONTHLY_OFF_PEAK___ICE_FUTURES_ENERGY_DIV_	 = 138	,
			MISO_IN__DAY_AHEAD_PEAK___ICE_FUTURES_ENERGY_DIV_	 = 139	,
			MISO_INDIANA_HUB_RT_PEAK___ICE_FUTURES_ENERGY_DIV_	 = 140	,
			PJM_N__IL_HUB_DA_OFF_PK____ICE_FUTURES_ENERGY_DIV_	 = 141	,
			PJM_N__IL_HUB_DA_PEAK___ICE_FUTURES_ENERGY_DIV_	 = 142	,
			ISO_NE_MASS_HUB_DA_OFF_PK___ICE_FUTURES_ENERGY_DIV_	 = 143	,
			ISO_NE_MASS_HUB_DA_PEAK___ICE_FUTURES_ENERGY_DIV_	 = 144	,
			CAISO_NP_15_PEAK___ICE_FUTURES_ENERGY_DIV_	 = 145	,
			CAISO_NP_15_OFF_PEAK___ICE_FUTURES_ENERGY_DIV_	 = 146	,
			PJM_NI_HUB_RT_OFF_PK___ICE_FUTURES_ENERGY_DIV_	 = 147	,
			PJM_N__IL_HUB_RT_PEAK___ICE_FUTURES_ENERGY_DIV_	 = 148	,
			NYISO_ZONE_J_DA_PEAK___ICE_FUTURES_ENERGY_DIV_	 = 149	,
			NYISO_ZONE_J_DA_OFF_PK___ICE_FUTURES_ENERGY_DIV_	 = 150	,
			NYISO_ZONE_A_DA_PEAK___ICE_FUTURES_ENERGY_DIV_	 = 151	,
			NYISO_ZONE_A_DA_OFF_PK___ICE_FUTURES_ENERGY_DIV_	 = 152	,
			NYISO_ZONE_G_DA_PEAK___ICE_FUTURES_ENERGY_DIV_	 = 153	,
			NYISO_ZONE_G_DA_OFF_PK___ICE_FUTURES_ENERGY_DIV_	 = 154	,
			PALO_VERDE_DA_PEAK___ICE_FUTURES_ENERGY_DIV_	 = 155	,
			PJM_BGE_ZONE_DAY_AHEAD_OFF_PEAK_MONTHLY___ICE_FUTURES_ENERGY_DIV_	 = 156	,
			PJM_BGE_ZONE_DAY_AHEAD__PEAK_MONTHLY___ICE_FUTURES_ENERGY_DIV_	 = 157	,
			PJM_PECO_ZONE_DA_PEAK___ICE_FUTURES_ENERGY_DIV_	 = 158	,
			PJM_PECO_ZONE_OFF_PEAK_MONTHLY___ICE_FUTURES_ENERGY_DIV_	 = 159	,
			PJM_PPL_ZONE_DAY_AHEAD__OFF_PEAK_MONTHLY___ICE_FUTURES_ENERGY_DIV_	 = 160	,
			PJM_PPL_ZONE_DA_PEAK___ICE_FUTURES_ENERGY_DIV_	 = 161	,
			PJM_WESTERN_HUB_DA_OFF_PK___ICE_FUTURES_ENERGY_DIV_	 = 162	,
			PJM_WESTERN_HUB_DA_PEAK___ICE_FUTURES_ENERGY_DIV_	 = 163	,
			PJM_WESTERN_HUB_RT_PEAK_MINI___ICE_FUTURES_ENERGY_DIV_	 = 164	,
			PJM_PSEG_DAY_AHEAD_PEAK___ICE_FUTURES_ENERGY_DIV_	 = 165	,
			PJM_PSEG_ZONE_DAY_AHEAD_OFF_PEAK___ICE_FUTURES_ENERGY_DIV_	 = 166	,
			ERCOT_N_345KV_REAL_T_PK_DALY_M___ICE_FUTURES_ENERGY_DIV_	 = 167	,
			ERCOT_N_345KV_REAL_T_PK_2x16___ICE_FUTURES_ENERGY_DIV_	 = 168	,
			ISONE__H_INTERNAL_HUB_month_on_dap___NODAL_EXCHANGE_	 = 169	,
			ISONE__H_INTERNAL_HUB_month_off_dap___NODAL_EXCHANGE_	 = 170	,
			MISO_INDIANA_HUB_month_on_dap___NODAL_EXCHANGE_	 = 171	,
			MISO_INDIANA_HUB_month_off_dap___NODAL_EXCHANGE_	 = 172	,
			NYISO_HUD_VL_month_on_dap___NODAL_EXCHANGE_	 = 173	,
			NYISO_HUD_VL_month_off_dap___NODAL_EXCHANGE_	 = 174	,
			NYISO_WEST_month_on_dap___NODAL_EXCHANGE_	 = 175	,
			PJM_AEP_DAYTON_HUB_month_on_dap___NODAL_EXCHANGE_	 = 176	,
			PJM_AEP_DAYTON_HUB_month_off_dap___NODAL_EXCHANGE_	 = 177	,
			PJM_BGE_month_on_dap___NODAL_EXCHANGE_	 = 178	,
			PJM_BGE_month_off_dap___NODAL_EXCHANGE_	 = 179	,
			PJM_JCPL_month_on_dap___NODAL_EXCHANGE_	 = 180	,
			PJM_JCPL_month_off_dap___NODAL_EXCHANGE_	 = 181	,
			PJM_N_ILLINOIS_HUB_month_on_dap___NODAL_EXCHANGE_	 = 182	,
			PJM_N_ILLINOIS_HUB_month_off_dap___NODAL_EXCHANGE_	 = 183	,
			PJM_PECO_month_on_dap___NODAL_EXCHANGE_	 = 184	,
			PJM_PECO_month_off_dap___NODAL_EXCHANGE_	 = 185	,
			PJM_PEPCO_month_on_dap___NODAL_EXCHANGE_	 = 186	,
			PJM_PEPCO_month_off_dap___NODAL_EXCHANGE_	 = 187	,
			PJM_PPL_month_on_dap___NODAL_EXCHANGE_	 = 188	,
			PJM_PPL_month_off_dap___NODAL_EXCHANGE_	 = 189	,
			PJM_PSEG_month_on_dap___NODAL_EXCHANGE_	 = 190	,
			PJM_PSEG_month_off_dap___NODAL_EXCHANGE_	 = 191	,
			PJM_WESTERN_HUB_month_on_dap___NODAL_EXCHANGE_	 = 192	,
			PJM_WESTERN_HUB_month_off_dap___NODAL_EXCHANGE_	 = 193	,
			PJM_AEP_DAYTON_HUB_month_on_rtp___NODAL_EXCHANGE_	 = 194	,
			PJM_AEP_DAYTON_HUB_month_off_rtp___NODAL_EXCHANGE_	 = 195	,
			PJM_N_ILLINOIS_HUB_month_on_rtp___NODAL_EXCHANGE_	 = 196	,
			PJM_N_ILLINOIS_HUB_month_off_rtp___NODAL_EXCHANGE_	 = 197	,
			PJM_WESTERN_HUB_month_on_rtp___NODAL_EXCHANGE_	 = 198	,
			PJM_WESTERN_HUB_month_off_rtp___NODAL_EXCHANGE_	 = 199	,
			PJM_ATSI_month_on_dap___NODAL_EXCHANGE_	 = 200	,
			PJM_ATSI_month_off_dap___NODAL_EXCHANGE_	 = 201	,
			PJM_DEOK_month_on_dap___NODAL_EXCHANGE_	 = 202	,
			ARGUS_CIF_ARA_Lg_Finl_Propane___ICE_FUTURES_ENERGY_DIV_	 = 203	,
			ARGUS_FAR_EAST_PROPANE___ICE_FUTURES_ENERGY_DIV_	 = 204	,
			ETHANE__MT__BELV_ENTERPRISE___ICE_FUTURES_ENERGY_DIV_	 = 205	,
			NAT_GASLNE_OPIS_MT_B_NONTET_FP___ICE_FUTURES_ENERGY_DIV_	 = 206	,
			BUTANE_OPIS_MT_BELV_NONTET_FP____ICE_FUTURES_ENERGY_DIV_	 = 207	,
			PROPANE_OPIS_MT_BELV_NONTET_FP___ICE_FUTURES_ENERGY_DIV_	 = 208	,
			PROPANE_OPIS_MT_BELVIEU_TET_FP___ICE_FUTURES_ENERGY_DIV_	 = 209	,
			PROPANE_ARGUS_SAUDI_CP_FP___ICE_FUTURES_ENERGY_DIV_	 = 210	,
			EUROPEAN_PROPANE_CIF_ARA___NEW_YORK_MERCANTILE_EXCHANGE_	 = 211	,
			ARGUS_PROPANE_SAUDI_ARAMCO___NEW_YORK_MERCANTILE_EXCHANGE_	 = 212	,
			ARGUS_PROPANE_FAR_EAST_INDEX___NEW_YORK_MERCANTILE_EXCHANGE_	 = 213	,
			PROPANE_NON_LDH_MT_BEL___NEW_YORK_MERCANTILE_EXCHANGE_	 = 214	,
			MT_BELVIEU_LDH_PROPANE__OPIS____NEW_YORK_MERCANTILE_EXCHANGE_	 = 215	,
			MT_BELVIEU_ETHANE_OPIS___NEW_YORK_MERCANTILE_EXCHANGE_	 = 216	,
			MT_BELV_NORM_BUTANE_OPIS___NEW_YORK_MERCANTILE_EXCHANGE_	 = 217	,
			MT_BELV_NAT_GASOLINE_OPIS___NEW_YORK_MERCANTILE_EXCHANGE_	 = 218	,
			CONWAY_PROPANE__OPIS____NEW_YORK_MERCANTILE_EXCHANGE_	 = 219	,
			MT_BELVIEU_LDH_PROPANE_BALMO____NEW_YORK_MERCANTILE_EXCHANGE_	 = 220	,
			MT_BELVIEU_NORMAL_BUTANE_BALMO___NEW_YORK_MERCANTILE_EXCHANGE_	 = 221	,
			CRUDE_OIL__LIGHT_SWEET_WTI___ICE_FUTURES_EUROPE_	 = 222	,
			WTI_CRUDE_OIL_1ST_LINE___ICE_FUTURES_ENERGY_DIV_	 = 223	,
			WTI_1st_Line_Brent_1st_Line___ICE_FUTURES_ENERGY_DIV_	 = 224	,
			CRUDE_DIFF_TMX_WCS_1A_INDEX___ICE_FUTURES_ENERGY_DIV_	 = 225	,
			ARGUS_MARS_vs_WTI_TRADE_MONTH___ICE_FUTURES_ENERGY_DIV_	 = 226	,
			CRUDE_DIFF_TMX_SW_1A_INDEX___ICE_FUTURES_ENERGY_DIV_	 = 227	,
			ARGUS_WTI_MidWTI_TRADE_MONTH___ICE_FUTURES_ENERGY_DIV_	 = 228	,
			CRUDE_OIL__LIGHT_SWEET___NEW_YORK_MERCANTILE_EXCHANGE_	 = 229	,
			WTI_FINANCIAL_CRUDE_OIL___NEW_YORK_MERCANTILE_EXCHANGE_	 = 230	,
			WTI_BRENT_CALENDAR___NEW_YORK_MERCANTILE_EXCHANGE_	 = 231	,
			BRENT_CRUDE_OIL_LAST_DAY___NEW_YORK_MERCANTILE_EXCHANGE_	 = 232	,
			WTI__HOUSTON_ARGUSWTI_TR_MO___NEW_YORK_MERCANTILE_EXCHANGE_	 = 233	,
			WTI_MIDLAND_ARGUS_VS_WTI_TRADE___NEW_YORK_MERCANTILE_EXCHANGE_	 = 234	,
			WCS_OIL_NET_ENERGY_MONTHLY_IND___NEW_YORK_MERCANTILE_EXCHANGE_	 = 235	,
			COCOA___ICE_FUTURES_U_S__	 = 236	,
			PALLADIUM___NEW_YORK_MERCANTILE_EXCHANGE_	 = 237	,
			PLATINUM___NEW_YORK_MERCANTILE_EXCHANGE_	 = 238	,
			SUGAR_NO__11___ICE_FUTURES_U_S__	 = 239	,
			COFFEE_C___ICE_FUTURES_U_S__	 = 240	,
			SILVER___COMMODITY_EXCHANGE_INC__	 = 241	,
			COPPER_GRADE__1___COMMODITY_EXCHANGE_INC__	 = 242	,
			GOLD___COMMODITY_EXCHANGE_INC__	 = 243	,
			GASOLINE_CRK_RBOBBRENT_1st___ICE_FUTURES_ENERGY_DIV_	 = 244	,
			GASOLINE_BLENDSTOCK__RBOB_____NEW_YORK_MERCANTILE_EXCHANGE_	 = 245	,
			RBOB_CALENDAR___NEW_YORK_MERCANTILE_EXCHANGE_	 = 246	,
			SINGAPORE_MOGUS_92___NEW_YORK_MERCANTILE_EXCHANGE_	 = 247	,
			GULF_COAST_UNL_87_GAS_M2_PL_RB___NEW_YORK_MERCANTILE_EXCHANGE_	 = 248	,
			GULF_COAST_CBOB_GAS_A2_PL_RBOB___NEW_YORK_MERCANTILE_EXCHANGE_	 = 249	,
			CANOLA___ICE_FUTURES_U_S__	 = 250	,
			ALUMINUM_MW_US_TR_PLATTS___COMMODITY_EXCHANGE_INC__	 = 251	,
			HOT_ROLLED_COIL_STEEL___NEW_YORK_MERCANTILE_EXCHANGE_	 = 252	,
			NFX_CS5TC_CAPESIZE_5TC_AVG___NASDAQ_FUTURES_	 = 253	,
			NFX_PM4TC_PANAMAX_4TC_AVG___NASDAQ_FUTURES_	 = 254	,
			NFX_SM10TC_SUPRAMAX_10TC_AVG___NASDAQ_FUTURES_	 = 255	,
			NFX_SM6TC_SUPRAMAX_6TC_AVG___NASDAQ_FUTURES_	 = 256	,
			GULF_JET_NY_HEAT_OIL_SPR___NEW_YORK_MERCANTILE_EXCHANGE_	 = 257	,
			SING_JET_KERO_GASOIL_SPR___NEW_YORK_MERCANTILE_EXCHANGE_	 = 258	,
			_3_5pct_FUEL_OIL_RDAM_CRACK_SPR____NEW_YORK_MERCANTILE_EXCHANGE_	 = 259	,
			NAPHTHA_CRACK_SPR___NEW_YORK_MERCANTILE_EXCHANGE_	 = 260	,
			MINI_JAPAN_CF_NAPHTHA___NEW_YORK_MERCANTILE_EXCHANGE_	 = 261	,
			EUROBOB_OXY_NWE_CRK_SPR____NEW_YORK_MERCANTILE_EXCHANGE_	 = 262	,
			MINI_SOYBEANS___CHICAGO_BOARD_OF_TRADE_	 = 263	,
			NJ_SRECS_VINTAGE_2018___ICE_FUTURES_ENERGY_DIV_	 = 264	,
			CALIF_CARBON_ALL_VINTAGE_2017___ICE_FUTURES_ENERGY_DIV_	 = 265	,
			PJM_TRI_RECs_CLASS_1_Vin_2018___ICE_FUTURES_ENERGY_DIV_	 = 266	,
			RGGI_VINTAGE_2017___ICE_FUTURES_ENERGY_DIV_	 = 267	,
			NY_RES_FUEL_1_0pct_SULFUR_SWAP___NEW_YORK_MERCANTILE_EXCHANGE_	 = 268	,
			SING_FUEL_OIL_180_CAL_SWAP___NEW_YORK_MERCANTILE_EXCHANGE_	 = 269	,
			GULF_3pct_FUEL_OIL_BALMO_SWAP___NEW_YORK_MERCANTILE_EXCHANGE_	 = 270	,
			TRANSCO_STN_85_MONTHLY_INDEX___ICE_FUTURES_ENERGY_DIV_	 = 271	,
			TETCO_M2_Index__Receipts____ICE_FUTURES_ENERGY_DIV_	 = 272	,
			TRANSCO_LEIDY_INDEX___ICE_FUTURES_ENERGY_DIV_	 = 273	,
			HENRY_HUB_NAT_GAS_FINL_10000___NASDAQ_FUTURES_	 = 274	,
			COAL__API_4__FOB__RICH_BAY_FUT___NEW_YORK_MERCANTILE_EXCHANGE_	 = 275	,
			JAPAN_CF_NAPHTHA_SWAP___NEW_YORK_MERCANTILE_EXCHANGE_	 = 276	,
			ERCOT_NORTH_345K_RT_OFFPK_DLY____ICE_FUTURES_ENERGY_DIV_	 = 277	,
			NYISO_ZONE_C_DA_PEAK___ICE_FUTURES_ENERGY_DIV_	 = 278	,
			PJM_RT_PEAK_CAL_1X___ICE_FUTURES_ENERGY_DIV_	 = 279	,
			PJM_COMED_ZONE_DAY_AHEAD_LMP_OFF_PEAK_MONTHLY___ICE_FUTURES_ENERGY_DIV_	 = 280	,
			PJM_COMED_ZONE_DAY_AHEAD_LMP_PEAK_MONTHLY___ICE_FUTURES_ENERGY_DIV_	 = 281	,
			PJM_JCPL_ZONE_DAY_AHEAD_PEAK____ICE_FUTURES_ENERGY_DIV_	 = 282	,
			PJM_PEPCO_DA_PEAK___ICE_FUTURES_ENERGY_DIV_	 = 283	,
			PJM_PEPCO_DAY_AHEAD_OFF_PEAK___ICE_FUTURES_ENERGY_DIV_	 = 284	,
			PJM_ATSI_DA_PEAK_FIXED___ICE_FUTURES_ENERGY_DIV_	 = 285	,
			PJM_ATSI_DA_OFFPEAK_FIXED___ICE_FUTURES_ENERGY_DIV_	 = 286	,
			PJM_WESTERN_PEAK_REAL_TIME___NEW_YORK_MERCANTILE_EXCHANGE_	 = 287	,
			MISO_AMIL_BGS6_DAY_AHEAD_PEAK____ICE_FUTURES_ENERGY_DIV_	 = 288	,
			RBOB_GASOLINEBRENT_CRACK_SPRD___NEW_YORK_MERCANTILE_EXCHANGE_	 = 289	,
			IRON_ORE_62pct_FE_CFR_CHINA_TSI___NEW_YORK_MERCANTILE_EXCHANGE_	 = 290	,
			JET_UP_DOWN_BALMO___NEW_YORK_MERCANTILE_EXCHANGE_	 = 291	,
			GULF___6_FUEL_OIL_CRACK_SWAP___NEW_YORK_MERCANTILE_EXCHANGE_	 = 292	,
			RTD_3_5pct_FUEL_OIL_CRK_SPD_SWP___NEW_YORK_MERCANTILE_EXCHANGE_	 = 293	,
			GULF_6_FUELOIL_BRENT_CRACK_SWP___NEW_YORK_MERCANTILE_EXCHANGE_	 = 294	,
			CALIF_CARBON_ALL_VINTAGE_2016___ICE_FUTURES_ENERGY_DIV_	 = 295	,
			NJ_SRECS_VINTAGE_2017___ICE_FUTURES_ENERGY_DIV_	 = 296	,
			RGGI_VINTAGE_2016___ICE_FUTURES_ENERGY_DIV_	 = 297	,
			PJM_TRI_RECs_CLASS_1_Vin_2017___ICE_FUTURES_ENERGY_DIV_	 = 298	,
			MINI_SING_FUELOIL_180_CAL_SWAP___NEW_YORK_MERCANTILE_EXCHANGE_	 = 299	,
			SING_GASOIL_SWAP___NEW_YORK_MERCANTILE_EXCHANGE_	 = 300	,
			NEW_YORK_ETHANOL_SWAP___NEW_YORK_MERCANTILE_EXCHANGE_	 = 301	,
			MISO_INDIANA_HUB_RT_PEAK_MINI___ICE_FUTURES_ENERGY_DIV_	 = 302	,
			ISO_NE_MASS_DA_OFF_PK_MINI___ICE_FUTURES_ENERGY_DIV_	 = 303	,
			ISO_NE_MASS_DA_PEAK_MINI___ICE_FUTURES_ENERGY_DIV_	 = 304	,
			NYISO_ZONE_C_DA_OFF_PK___ICE_FUTURES_ENERGY_DIV_	 = 305	,
			NYISO_ZONE_F_PEAK_MONTHLY___ICE_FUTURES_ENERGY_DIV_	 = 306	,
			PALO_VERDE_DA_OFF_PK___ICE_FUTURES_ENERGY_DIV_	 = 307	,
			PJM_WESTERN_HUB_RT_OFF_PK_MINI___ICE_FUTURES_ENERGY_DIV_	 = 308	,
			AEP_DAYTON_REALTIME_OFFPEAK_MI___ICE_FUTURES_ENERGY_DIV_	 = 309	,
			MISO_IN__REALTIME_OFFPEAK_MINI___ICE_FUTURES_ENERGY_DIV_	 = 310	,
			PJM_WESTERN_HUB_RT_OFF_5_MW___NEW_YORK_MERCANTILE_EXCHANGE_	 = 311	,
			NYISO_ZONE_A_DAY_AHEAD_PEAK_MI___ICE_FUTURES_ENERGY_DIV_	 = 312	,
			NYISO_ZONE_A_DAY_AHEAD_OFFPEAK___ICE_FUTURES_ENERGY_DIV_	 = 313	,
			NYISO_ZONE_G_DAY_AHEAD_PEAK_MI___ICE_FUTURES_ENERGY_DIV_	 = 314	,
			NYISO_ZONE_G_DAY_AHEAD_OFFPEAK___ICE_FUTURES_ENERGY_DIV_	 = 315	,
			NYISO_ZONE_J_DAY_AHEAD_PEAK_MI___ICE_FUTURES_ENERGY_DIV_	 = 316	,
			NYISO_ZONE_J_DAY_AHEAD_OFFPEAK___ICE_FUTURES_ENERGY_DIV_	 = 317	,
			PJM_AEP_DAYTON_REAL_PEAK_MINI___ICE_FUTURES_ENERGY_DIV_	 = 318	,
			PJM_NI_HUB_REALTM_OFFPEAK_MINI___ICE_FUTURES_ENERGY_DIV_	 = 319	,
			PJM_NI_HUB_REALTIME_PEAK_MINI___ICE_FUTURES_ENERGY_DIV_	 = 320	,
			CANADIAN_HVY_CRUDE_NET_ENRGY____NEW_YORK_MERCANTILE_EXCHANGE_	 = 321	,
			MINI_EUROBOB_GAS_OXY_NWE___NEW_YORK_MERCANTILE_EXCHANGE_	 = 322	,
			JAPAN_CF_NAPHTHA_CRK_SPR_SWAP___NEW_YORK_MERCANTILE_EXCHANGE_	 = 323	,
			MINI_CORN___CHICAGO_BOARD_OF_TRADE_	 = 324	,
			SULFUR_FINANCIAL_INSTRUMENT___CHICAGO_CLIMATE_FUTURES_EXCHANGE_	 = 325	,
			SULFUR_FINANCIAL_INSTR_2009___CHICAGO_CLIMATE_FUTURES_EXCHANGE_	 = 326	,
			CARBON_FINANCIAL_INSTRUMENT___CHICAGO_CLIMATE_FUTURES_EXCHANGE_	 = 327	,
			NITROGEN_FIN_INS_ANNUAL_2009___CHICAGO_CLIMATE_FUTURES_EXCHANGE_	 = 328	,
			RGGI_CO2_ALLOWANCE_2009___CHICAGO_CLIMATE_FUTURES_EXCHANGE_	 = 329	,
			CALIF_CARBON_ALLOWANCE_2013___ICE_FUTURES_ENERGY_DIV_	 = 330	,
			CALIFORNIA_CARBON_ALLOWANCE_VINTAGE_2014___ICE_FUTURES_ENERGY_DIV_	 = 331	,
			CALIFORNIA_CARBON_ALLOWANCE_VINTAGE_2015___ICE_FUTURES_ENERGY_DIV_	 = 332	,
			RGGI_VINTAGE_2014___ICE_FUTURES_ENERGY_DIV_	 = 333	,
			NJ_SRECS_VINTAGE_2016___ICE_FUTURES_ENERGY_DIV_	 = 334	,
			RGGI_VINTAGE_2015___ICE_FUTURES_ENERGY_DIV_	 = 335	,
			IN_DELIVERY_MONTH_EUA___NEW_YORK_MERCANTILE_EXCHANGE_	 = 336	,
			EUR_1pct_FUEL_OIL_NWE_CAL_SWAP___NEW_YORK_MERCANTILE_EXCHANGE_	 = 337	,
			FUEL_OIL_CARGOES_B_PLATTS_SWAP___NEW_YORK_MERCANTILE_EXCHANGE_	 = 338	,
			EAST_WEST_FUEL_OIL_SPR_SWAP___NEW_YORK_MERCANTILE_EXCHANGE_	 = 339	,
			SING_180_380_FUEL_OIL_SPR_SWAP___NEW_YORK_MERCANTILE_EXCHANGE_	 = 340	,
			_3_5pct_FUEL_OIL_RDAM_V__FOB_MED___NEW_YORK_MERCANTILE_EXCHANGE_	 = 341	,
			NY_1pct_V_GULF_3pct_FUEL_OIL_SPR____NEW_YORK_MERCANTILE_EXCHANGE_	 = 342	,
			MINI_EUR_3_5pctFOIL_RTD_BALMOSWP___NEW_YORK_MERCANTILE_EXCHANGE_	 = 343	,
			NY_FO_1pct_v_EUR_1pct_FO_FOB_NWE___NEW_YORK_MERCANTILE_EXCHANGE_	 = 344	,
			SING_GASOIL_ICE_GASOIL_SWAP___NEW_YORK_MERCANTILE_EXCHANGE_	 = 345	,
			NYMEX_HEATING_OILRDAM_GASOIL___NEW_YORK_MERCANTILE_EXCHANGE_	 = 346	,
			GASOIL__ICE__SWAP___NEW_YORK_MERCANTILE_EXCHANGE_	 = 347	,
			GULF_COAST_ULSD_SWAP___NEW_YORK_MERCANTILE_EXCHANGE_	 = 348	,
			GULF_COAST_ULSD_PLATT_CRACK____NEW_YORK_MERCANTILE_EXCHANGE_	 = 349	,
			ULSD_UP_DOWN_SWAP___NEW_YORK_MERCANTILE_EXCHANGE_	 = 350	,
			SING_GASOIL_BALMO_SWAP___NEW_YORK_MERCANTILE_EXCHANGE_	 = 351	,
			GASOIL__ICE__MINI_CAL_SWAP___NEW_YORK_MERCANTILE_EXCHANGE_	 = 352	,
			GASOIL_0_1_BARGE_FOB_RDM_V_ICE___NEW_YORK_MERCANTILE_EXCHANGE_	 = 353	,
			GRP_3_ULSD_VS_HEATING_OIL_SPR___NEW_YORK_MERCANTILE_EXCHANGE_	 = 354	,
			ULSD_UP_DOWN_BALMO_SWAP___NEW_YORK_MERCANTILE_EXCHANGE_	 = 355	,
			NY_ULSD_VS_HEATING_OIL_SPR_SWP___NEW_YORK_MERCANTILE_EXCHANGE_	 = 356	,
			SONAT___TIER_1_POOL__ZONE_0____ICE_FUTURES_ENERGY_DIV_	 = 357	,
			TENNESSEE_GAS_PIPELINE_CO____ZONE_L__500_LEG_POOL___ICE_FUTURES_ENERGY_DIV_	 = 358	,
			TRANSCONTINENTAL_GAS_PIPELINE_CORP____ZONE_6__NY____ICE_FUTURES_ENERGY_DIV_	 = 359	,
			E_MINI_NATURAL_GAS___NEW_YORK_MERCANTILE_EXCHANGE_	 = 360	,
			MICHCON_BASIS_SWAP___NEW_YORK_MERCANTILE_EXCHANGE_	 = 361	,
			PERMIAN_BASIS_SWAP___NEW_YORK_MERCANTILE_EXCHANGE_	 = 362	,
			M_3_BASIS_SWAP___NEW_YORK_MERCANTILE_EXCHANGE_	 = 363	,
			TCO_BASIS_SWAP___NEW_YORK_MERCANTILE_EXCHANGE_	 = 364	,
			MALIN_BASIS_SWAP___NEW_YORK_MERCANTILE_EXCHANGE_	 = 365	,
			PGE_CITYGATE_BASIS_SWAP___NEW_YORK_MERCANTILE_EXCHANGE_	 = 366	,
			NGPL_TEXOK_BASIS_SWAP___NEW_YORK_MERCANTILE_EXCHANGE_	 = 367	,
			SUMAS_BASIS_SWAP___NEW_YORK_MERCANTILE_EXCHANGE_	 = 368	,
			NGPL_MIDCON_BASIS_SWAP___NEW_YORK_MERCANTILE_EXCHANGE_	 = 369	,
			DEMARC_BASIS_SWAP___NEW_YORK_MERCANTILE_EXCHANGE_	 = 370	,
			VENTURA_BASIS_SWAP___NEW_YORK_MERCANTILE_EXCHANGE_	 = 371	,
			DOMINION_BASIS_SWAP___NEW_YORK_MERCANTILE_EXCHANGE_	 = 372	,
			WAHA_BASIS_SWAP___NEW_YORK_MERCANTILE_EXCHANGE_	 = 373	,
			CIG_ROCKIES_BASIS_SWAP___NEW_YORK_MERCANTILE_EXCHANGE_	 = 374	,
			TRANSCO_ZONE_3_BASIS_SWAP___NEW_YORK_MERCANTILE_EXCHANGE_	 = 375	,
			COLUMBIA_GULF_ONSHORE_SWAP___NEW_YORK_MERCANTILE_EXCHANGE_	 = 376	,
			HENRY_HUB_INDEX_SWAP___NEW_YORK_MERCANTILE_EXCHANGE_	 = 377	,
			HOUSTON_SHIP_CH_INDEX_SWAP___NEW_YORK_MERCANTILE_EXCHANGE_	 = 378	,
			WAHA_INDEX_SWAP___NEW_YORK_MERCANTILE_EXCHANGE_	 = 379	,
			SOCAL_INDEX_SWAP___NEW_YORK_MERCANTILE_EXCHANGE_	 = 380	,
			TETCO_M_3_INDEX_SWAP___NEW_YORK_MERCANTILE_EXCHANGE_	 = 381	,
			TRANSCO_ZONE_4_BASIS_SWAP___NEW_YORK_MERCANTILE_EXCHANGE_	 = 382	,
			CENTERPOINT_BASIS_SWAP___NEW_YORK_MERCANTILE_EXCHANGE_	 = 383	,
			COLUMBIA_GULF_ML_SWAP___NEW_YORK_MERCANTILE_EXCHANGE_	 = 384	,
			CENTRAL_APPALACHIAN_COAL___NEW_YORK_MERCANTILE_EXCHANGE_	 = 385	,
			CSX_COAL_SWAP___NEW_YORK_MERCANTILE_EXCHANGE_	 = 386	,
			POWDER_RIVER_BASIN_COAL_SWAP___NEW_YORK_MERCANTILE_EXCHANGE_	 = 387	,
			SING_NAPHTHA_SWAP___NEW_YORK_MERCANTILE_EXCHANGE_	 = 388	,
			ALBERTA_BASIS_SWAP___NEW_YORK_MERCANTILE_EXCHANGE_	 = 389	,
			CHICAGO_BASIS_SWAP___NEW_YORK_MERCANTILE_EXCHANGE_	 = 390	,
			HENRY_HUB_BASIS_SWAP___NEW_YORK_MERCANTILE_EXCHANGE_	 = 391	,
			HOUSTON_SHIP_CH_BASIS_SWAP___NEW_YORK_MERCANTILE_EXCHANGE_	 = 392	,
			NW_PIPE_ROCKIES_BASIS_SWAP___NEW_YORK_MERCANTILE_EXCHANGE_	 = 393	,
			PANHANDLE_BASIS_SWAP___NEW_YORK_MERCANTILE_EXCHANGE_	 = 394	,
			SAN_JUAN_BASIS_SWAP___NEW_YORK_MERCANTILE_EXCHANGE_	 = 395	,
			SOCAL_BASIS_SWAP___NEW_YORK_MERCANTILE_EXCHANGE_	 = 396	,
			TRANSCO_ZONE_6_BASIS_SWAP___NEW_YORK_MERCANTILE_EXCHANGE_	 = 397	,
			FRZN_PORK_BELLIES___CHICAGO_MERCANTILE_EXCHANGE_	 = 398	,
			NYISO_ZONE_F_DA_OFFPEAK___ICE_FUTURES_ENERGY_DIV_	 = 399	,
			ISO_NEW_ENGLAND_CT_DA_LMP_OFF_PEAK_MONTHLY___ICE_FUTURES_ENERGY_DIV_	 = 400	,
			ISO_NE_CONN_DA_PEAK___ICE_FUTURES_ENERGY_DIV_	 = 401	,
			PJM_EASTERN_HUB_DAY_AHEAD___ICE_FUTURES_ENERGY_DIV_	 = 402	,
			PJM_JCPL_ZONE_DAY_AHEAD_OFF_PEAK___ICE_FUTURES_ENERGY_DIV_	 = 403	,
			PJM_WESTERN_HUB_RT_PEAK_2_5MW___NEW_YORK_MERCANTILE_EXCHANGE_	 = 404	,
			NYISO_ZONE_A_LBMP_SWAP___NEW_YORK_MERCANTILE_EXCHANGE_	 = 405	,
			NYISO_ZONE_G_LBMP_SWAP___NEW_YORK_MERCANTILE_EXCHANGE_	 = 406	,
			NYISO_ZONE_J_LBMP_SWAP___NEW_YORK_MERCANTILE_EXCHANGE_	 = 407	,
			ISO_NEW_ENGLAND_LMP_SWAP___NEW_YORK_MERCANTILE_EXCHANGE_	 = 408	,
			NORTH_ILL_CAL_MONTH_LMP_OPT___NEW_YORK_MERCANTILE_EXCHANGE_	 = 409	,
			AEP_DAYTON_PEAKCAL_MONTH_LMP_5___NEW_YORK_MERCANTILE_EXCHANGE_	 = 410	,
			PJM_CAL_MONTH_OFF_PK_LMP_SWAP___NEW_YORK_MERCANTILE_EXCHANGE_	 = 411	,
			NORTH_ILL_OFF_PK_LMP_SWAP___NEW_YORK_MERCANTILE_EXCHANGE_	 = 412	,
			AEP_DAYTON_OFF_PK_LMP_SWAP___NEW_YORK_MERCANTILE_EXCHANGE_	 = 413	,
			NYISO_ZONE_A_OFF_PK_LBMP_SWAP___NEW_YORK_MERCANTILE_EXCHANGE_	 = 414	,
			ISO_NEW_ENG_OFF_PK_LMP_SWAP___NEW_YORK_MERCANTILE_EXCHANGE_	 = 415	,
			ISO_NEW_ENG_CONN_PEAK_SWAP___NEW_YORK_MERCANTILE_EXCHANGE_	 = 416	,
			CINERGY_CAL_MONTH_LMP_SWAP___NEW_YORK_MERCANTILE_EXCHANGE_	 = 417	,
			CINERGY_OFF_PEAK_LMP_SWAP___NEW_YORK_MERCANTILE_EXCHANGE_	 = 418	,
			PJM_N_ILL_PEAK_DAY_AHEAD___NEW_YORK_MERCANTILE_EXCHANGE_	 = 419	,
			PJM_N_ILL_OFF_PEAK_DAY_AHEAD___NEW_YORK_MERCANTILE_EXCHANGE_	 = 420	,
			PJM_AEP_PEAK_DAY_AHEAD___NEW_YORK_MERCANTILE_EXCHANGE_	 = 421	,
			PJM_AEP_OFF_PEAK_DAY_AHEAD___NEW_YORK_MERCANTILE_EXCHANGE_	 = 422	,
			PJM_BGE_PEAK_DAY_AHEAD___NEW_YORK_MERCANTILE_EXCHANGE_	 = 423	,
			PJM_JCPL_PEAK_DAY_AHEAD___NEW_YORK_MERCANTILE_EXCHANGE_	 = 424	,
			PJM_JCPL_OFF_PEAK_DAY_AHEAD___NEW_YORK_MERCANTILE_EXCHANGE_	 = 425	,
			PJM_PEPCO_PEAK_DAY_AHEAD___NEW_YORK_MERCANTILE_EXCHANGE_	 = 426	,
			PJM_PEPCO_OFF_PEAK_DAY_AHEAD___NEW_YORK_MERCANTILE_EXCHANGE_	 = 427	,
			PJM_PPL_PEAK_DAY_AHEAD___NEW_YORK_MERCANTILE_EXCHANGE_	 = 428	,
			PJM_PPL_OFF_PEAK_DAY_AHEAD___NEW_YORK_MERCANTILE_EXCHANGE_	 = 429	,
			PJM_PSEG_PEAK_DAY_AHEAD___NEW_YORK_MERCANTILE_EXCHANGE_	 = 430	,
			PJM_PSEG_OFF_PEAK_DAY_AHEAD___NEW_YORK_MERCANTILE_EXCHANGE_	 = 431	,
			PJM_WESTERN_PEAK_DAY_AHEAD___NEW_YORK_MERCANTILE_EXCHANGE_	 = 432	,
			PJM_WESTERN_OFF_PEAK_DAY_AHEAD___NEW_YORK_MERCANTILE_EXCHANGE_	 = 433	,
			ISO_NEW_ENG_INT_HUB_PEAK_SWAP___NEW_YORK_MERCANTILE_EXCHANGE_	 = 434	,
			MW_IND_TR_REAL_TIME_PEAK_SWAP___NEW_YORK_MERCANTILE_EXCHANGE_	 = 435	,
			MW_IND_TRANS_PEAK_SWAP___NEW_YORK_MERCANTILE_EXCHANGE_	 = 436	,
			PJM_N_ILL_HUB_5_MW_PEAK_SWAP___NEW_YORK_MERCANTILE_EXCHANGE_	 = 437	,
			PJM_AEP_DAY_HUB_5_MW_PEAK_SWAP___NEW_YORK_MERCANTILE_EXCHANGE_	 = 438	,
			NYISO_ZONE_A_5_MW_PEAK_SWAP___NEW_YORK_MERCANTILE_EXCHANGE_	 = 439	,
			NYISO_ZONE_G_5_MW_PEAK___NEW_YORK_MERCANTILE_EXCHANGE_	 = 440	,
			NYISO_ZONE_J_5_MW_PEAK_SWAP___NEW_YORK_MERCANTILE_EXCHANGE_	 = 441	,
			ISO_NEW_ENG_CONN_OFF_PEAK_SWAP___NEW_YORK_MERCANTILE_EXCHANGE_	 = 442	,
			ISO_NEW_ENG_HUB_OFF_PEAK_SWAP___NEW_YORK_MERCANTILE_EXCHANGE_	 = 443	,
			PJM_N_ILL_HUB_5_OFF_PEAK_SWAP___NEW_YORK_MERCANTILE_EXCHANGE_	 = 444	,
			PJM_AEP_DAYTON_OFF_PEAK_SWAP___NEW_YORK_MERCANTILE_EXCHANGE_	 = 445	,
			NYISO_ZONE_A_5MW_OFF_PEAK_SWAP___NEW_YORK_MERCANTILE_EXCHANGE_	 = 446	,
			NYISO_ZONE_G_5_MW_OFF_PEAK___NEW_YORK_MERCANTILE_EXCHANGE_	 = 447	,
			NYISO_ZONE_J5_MW_OFF_PEAK_SWAP___NEW_YORK_MERCANTILE_EXCHANGE_	 = 448	,
			MW_CINRGY_5_OFF_PEAK_REAL_TIME___NEW_YORK_MERCANTILE_EXCHANGE_	 = 449	,
			MW_CINERGY_OFF_PEAK_CAL_MONTH___NEW_YORK_MERCANTILE_EXCHANGE_	 = 450	,
			PJM_WESTERN_HUB_REAL_OFF_DAY_5___NEW_YORK_MERCANTILE_EXCHANGE_	 = 451	,
			PJM_EASTERN_HUB_month_on_dap___NODAL_EXCHANGE_	 = 452	,
			MISO_INDIANA_HUB_month_on_rtp___NODAL_EXCHANGE_	 = 453	,
			ERCOT_NORTH_345KV_REAL_TIME_PK___ICE_FUTURES_ENERGY_DIV_	 = 454	,
			MT_BELVIEU_PROPANE_SWAP___NEW_YORK_MERCANTILE_EXCHANGE_	 = 455	,
			MT_BELVIEU_NAT_GASOLINE_SWAP___NEW_YORK_MERCANTILE_EXCHANGE_	 = 456	,
			MT_BELVIEU_NORMAL_BUTANE_SWAP___NEW_YORK_MERCANTILE_EXCHANGE_	 = 457	,
			MT_BELV_NORM_BUT_LDH_OPIS_SWP___NEW_YORK_MERCANTILE_EXCHANGE_	 = 458	,
			E_MINI_CRUDE_OIL__LIGHT_SWEET___NEW_YORK_MERCANTILE_EXCHANGE_	 = 459	,
			DUBAI_CRUDE_OIL_CALENDAR_SWAP___NEW_YORK_MERCANTILE_EXCHANGE_	 = 460	,
			WTI_CRUDE_OIL_FINANCIAL___NEW_YORK_MERCANTILE_EXCHANGE_	 = 461	,
			BRENT_FINANCIAL___NEW_YORK_MERCANTILE_EXCHANGE_	 = 462	,
			DATED_TO_FRONTLINE_BRENT_SWAP___NEW_YORK_MERCANTILE_EXCHANGE_	 = 463	,
			BRENT__ICE__CALENDAR_SWAP___NEW_YORK_MERCANTILE_EXCHANGE_	 = 464	,
			BRENT_DUBAI_SWAP___NEW_YORK_MERCANTILE_EXCHANGE_	 = 465	,
			OMAN_CRUDE_OIL___DUBAI_MERCANTILE_EXCHANGE_	 = 466	,
			RBOB_GASOLINE_FINANCIAL___NEW_YORK_MERCANTILE_EXCHANGE_	 = 467	,
			RBOB_UP_DOWN_CAL___NEW_YORK_MERCANTILE_EXCHANGE_	 = 468	,
			CHICAGO_HDD___CHICAGO_MERCANTILE_EXCHANGE_	 = 469	,
			NEW_YORK_CDD___CHICAGO_MERCANTILE_EXCHANGE_	 = 470	,
			NEW_YORK_HDD___CHICAGO_MERCANTILE_EXCHANGE_	 = 471	,
			GULF_COAST_JET_FUEL_CAL_SWAP___NEW_YORK_MERCANTILE_EXCHANGE_	 = 472	,
			SING_JET_KERO_SWAP___NEW_YORK_MERCANTILE_EXCHANGE_	 = 473	,
			JET_CIF_NWEGASOIL_FUT___NEW_YORK_MERCANTILE_EXCHANGE_	 = 474	,
			_1pct_FUEL_OIL_NWE_CRACK_SPR___NEW_YORK_MERCANTILE_EXCHANGE_	 = 475	,
			MINI_EUROPE_NAPHTHA_BALMO_SWAP___NEW_YORK_MERCANTILE_EXCHANGE_	 = 476	,
			GASOIL_CRACK_SPR_SWAP___NEW_YORK_MERCANTILE_EXCHANGE_	 = 477	,
			FAM_BIODIESEL_V_GASOIL_SPR_SWP___NEW_YORK_MERCANTILE_EXCHANGE_	 = 478	,
			FAME_BIODIESEL_V_GASOIL_SPR_SP___NEW_YORK_MERCANTILE_EXCHANGE_	 = 479	,
			RBOB_CRACK_SPREAD_SWAP___NEW_YORK_MERCANTILE_EXCHANGE_	 = 480	


		}
		
		static public string GetTicker(ECOTCmdtsCodes cotId)
		{
			string[,] values = new string[,] {
				{	"COT.CmdtsFut.001602",		"WHEAT-SRW - CHICAGO BOARD OF TRADE"	},
				{	"COT.CmdtsFut.00160F",		"BLACK SEA WHEAT FINANCIAL - CHICAGO BOARD OF TRADE"	},
				{	"COT.CmdtsFut.001612",		"WHEAT-HRW - CHICAGO BOARD OF TRADE"	},
				{	"COT.CmdtsFut.001626",		"WHEAT-HRSpring - MINNEAPOLIS GRAIN EXCHANGE"	},
				{	"COT.CmdtsFut.002602",		"CORN - CHICAGO BOARD OF TRADE"	},
				{	"COT.CmdtsFut.004603",		"OATS - CHICAGO BOARD OF TRADE"	},
				{	"COT.CmdtsFut.005602",		"SOYBEANS - CHICAGO BOARD OF TRADE"	},
				{	"COT.CmdtsFut.0063A2",		"CALIF CARBON ALL VINTAGE 2018 - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.0063A3",		"NJ SRECS VINTAGE 2019 - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.0063A4",		"NJ SRECS VINTAGE 2020 - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.0063AD",		"PJM TRI-RECs CLASS 1 Vin 2019 - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.0063AM",		"MASS RECs CLASS 1 Vin 2018 - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.0063AN",		"PJM TRI-RECs CLASS 1 Vin 2020 - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.0063AQ",		"MASS RECs CLASS 1 Vin 2019 - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.0063AS",		"CALIF CARBON ALL VINTAGE 2019 - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.0063B1",		"PJM TRI-RECs CLASS 1 Vin 2021 - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.0063BD",		"NJ SRECS VINTAGE 2021 - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.0063BF",		"NJ SRECS VINTAGE 2022 - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.0063BY",		"MASS RECs CLASS 1 Vin 2020 - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.0063CA",		"CALIF CARBON VINTAGE 2020 - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.0063CC",		"NJ SRECS - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.0063CD",		"RGGI VINTAGE 2018 - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.0063CH",		"PJM TRI-RECs CLASS 1  - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.0063CJ",		"CALIF CARBON VINTAGE 2021 - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.0063CL",		"RGGI VINTAGE 2019 - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.0063D9",		"CALIF CARBON ALLOWANCE V2022 - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.0063DK",		"CT RECs CLASS 1  - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.0063DL",		"MASS COMPLIANCE RECs CLASS 1  - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.0063DN",		"MARYLAND SOLAR REC - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.0063DP",		"MASS SREC CARVE OUT 1 - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.007601",		"SOYBEAN OIL - CHICAGO BOARD OF TRADE"	},
				{	"COT.CmdtsFut.02141B",		"USGC HSFO (PLATTS) - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.02141C",		"FUEL OIL-3% USGC/3.5% FOB RDAM BARGES - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.02141R",		"USGC HSFO-PLATTS/BRENT 1ST LN  - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.02141V",		"FUEL OIL NY 1% / GULF COAST 3% - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.02165A",		"GULF # 6 FUEL 3.0% SULFUR - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.02165E",		"EUR 3.5% FUEL OIL RTD CAL - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.02165K",		"SING FUEL OIL 380 cst PLATTS - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.021A17",		"MINI EUR 3.5%FOIL RTD CAL - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.021A28",		"GULF NO6 FO 3% v EUR 3.5% RDAM - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.021A35",		"MINI SING 380 FUEL OIL - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.021A56",		"FUEL OIL-380cst SING/3.5% RDAM - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.022651",		"#2 HEATING OIL- NY HARBOR-ULSD - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.022A13",		"UP DOWN GC ULSD VS HO SPR - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.023391",		"NATURAL GAS HENRY LD1 FIXED - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.023392",		"NATURAL GAS PENULTIMATE ICE - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.023393",		"SOCAL BORDER FIN BASIS - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.023394",		"PG&E CITYGATE FIN BASIS - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.023395",		"NWP ROCKIES FIN BASIS - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.023396",		"AECO FIN BASIS - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.023397",		"CHICAGO FIN BASIS - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.023398",		"HSC FIN BASIS - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.023399",		"WAHA FIN BASIS - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.02339E",		"ALGONQUIN CITY-GATES FINANCIAL BASIS - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.02339Q",		"CHICAGO CITYGATE (INDEX) - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.02339U",		"COLORADO INTERSTATE - MAINLINE (BASIS) - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.02339W",		"COLUMBIA GAS CO. - TCO POOL (APPALACHIA) (BASIS) - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.02339Y",		"COLUMBIA GULF TRANSMISSION CO. -  MAINLINE POOL - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.0233A2",		"DOMINION - SOUTH POINT - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.0233A3",		"DOMINION - SOUTH POINT (BASIS) - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.0233A5",		"EL PASO - PERMIAN BASIN (BASIS) - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.0233A6",		"EL PASO - PERMIAN BASIN (INDEX) - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.0233A8",		"EL PASO-SAN JUAN BASIN-BLANCO POOL PRIMARY ONLY-BASIS - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.0233AG",		"HENRY HUB - TAILGATE LOUISIANA (BASIS) - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.0233AH",		"HENRY HUB - TAILGATE LOUISIANA (INDEX) - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.0233AM",		"HOUSTON SHIP CHANNEL (INDEX) - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.0233AN",		"MICHCON FINANCIAL INDEX - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.0233AQ",		"MICHIGAN CONSOLIDATED CITYGATE (GENERIC) (BASIS) - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.0233AT",		"NAT GAS LD1 for GDD -TEXOK - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.0233AW",		"NATURAL GAS INDEX: ALGONQUIN CITY GATES - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.0233AY",		"NATURAL GAS PIPELINE-MID-CONTINENT POOL PIN (BASIS) - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.0233B1",		"NATURAL GAS PIPELINE-TEXOK (BASIS) - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.0233B7",		"NNG VENTURA FINANCIAL INDEX - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.0233BA",		"NORTHERN NATURAL GAS - DEMARCATION POOL (BASIS) - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.0233BB",		"NORTHERN NATURAL GAS - VENTURA (BASIS) - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.0233BC",		"NORTHWEST PIPELINE - CANADIAN BORDER (BASIS) - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.0233BD",		"NORTHWEST PIPELINE CORP. - ROCKY MOUNTAINS - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.0233BH",		"PACIFIC GAS TRANSMISSION - MALIN (BASIS) - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.0233BL",		"PANHANDLE EASTERN- POOL GAS (BASIS) - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.0233BM",		"PANHANDLE EASTERN- POOL GAS (INDEX) - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.0233BQ",		"PG&E - CITYGATE (INDEX) - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.0233BW",		"SOCAL (INDEX) - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.0233BY",		"SOCAL CITYGATE FINANCIAL BASIS - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.0233CG",		"TEXAS EASTERN- M3 ZONE (DELIVERED) - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.0233CH",		"TEXAS EASTERN- M3 ZONE (DELIVERED) (BASIS) - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.0233CU",		"TRANSCO ZONE 6 BASIS - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.0233CV",		"TRANSCO ZONE 6 MONTHLY INDEX - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.0233CW",		"TRANSCONTINENTAL GAS- STATION 85 (ZONE 4) - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.0233CZ",		"TRANSCONTINENTAL GAS - ZONE 6 (NY) (BASIS) - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.0233D4",		"WAHA HUB - WEST TEXAS DELIVERED/BUYER'S INDEX - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.0233DR",		"TETCO M2 Basis (Receipts) - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.0233DT",		"TRANSCO LEIDY BASIS - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.0233EB",		"REX ZONE 3 BASIS - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.0233ED",		"REX ZONE 3 INDEX - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.023651",		"NATURAL GAS - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.023A55",		"HENRY HUB LAST DAY FIN - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.023A56",		"HENRY HUB PENULTIMATE FIN - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.023P02",		"HHUB NAT GAS PENULT FINL-10000 - NASDAQ FUTURES"	},
				{	"COT.CmdtsFut.023P03",		"HHUB NAT GAS PENULT FINL-2500 - NASDAQ FUTURES"	},
				{	"COT.CmdtsFut.024656",		"COAL (API 2) CIF ARA - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.025601",		"CBT ETHANOL - CHICAGO BOARD OF TRADE"	},
				{	"COT.CmdtsFut.025608",		"ETHANOL T2 FOB INCL DUTY - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.025651",		"CHICAGO ETHANOL - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.026603",		"SOYBEAN MEAL - CHICAGO BOARD OF TRADE"	},
				{	"COT.CmdtsFut.03265A",		"EUROPEAN NAPHTHA CAL - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.03265J",		"Mini Eur Naphtha CIF NEW - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.033661",		"COTTON NO. 2 - ICE FUTURES U.S."	},
				{	"COT.CmdtsFut.03565B",		"HENRY HUB - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.03565C",		"HENRY HUB PENULTIMATE NAT GAS - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.037642",		"MALAYSIAN PALM OIL CALENDAR SW - CHICAGO MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.039601",		"ROUGH RICE - CHICAGO BOARD OF TRADE"	},
				{	"COT.CmdtsFut.040701",		"FRZN CONCENTRATED ORANGE JUICE - ICE FUTURES U.S."	},
				{	"COT.CmdtsFut.050642",		"BUTTER (CASH SETTLED) - CHICAGO MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.052641",		"MILK: Class III - CHICAGO MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.052642",		"NON FAT DRY MILK - CHICAGO MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.052644",		"CME MILK IV - CHICAGO MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.052645",		"DRY WHEY - CHICAGO MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.054642",		"LEAN HOGS - CHICAGO MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.057642",		"LIVE CATTLE - CHICAGO MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.058643",		"RANDOM LENGTH LUMBER - CHICAGO MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.061641",		"FEEDER CATTLE - CHICAGO MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.063642",		"CHEESE (CASH-SETTLED) - CHICAGO MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.064363",		"PJM WH REAL TIME PEAK - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.064391",		"MID-C DAY-AHEAD PEAK - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.064392",		"MID-C DAY-AHEAD OFF-PEAK - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.064394",		"PJM WESTERN HUB RT OFF - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.064395",		"SP15 FIN DA PEAK FIXED - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.064396",		"CAISO SP15 FIN DA OFF-PEAK - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.06439A",		"PJM AEP DAYTON RT OFF-PK - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.06439B",		"PJM AEP DAYTON RT PEAK FIXED - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.06439C",		"PJM AEP DAYTON HUB DA OFF-PK  - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.06439E",		"AD HUB DA PEAK DAILY - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.06439F",		"PJM AEP DAYTON DA PEAK - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.06439K",		"MISO INDIANA  OFF-PEAK - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.06439L",		"MISO IN. REAL-TIME OFF-PEAK - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.06439N",		"ERCOT HOUSTON 345KV RT PK FIX - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.06439R",		"ERCOT NORTH 345KV RT PK FIX - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.0643A5",		"ERCOT NORTH 345KV DA PK DLY FI - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.0643A8",		"ERCOT - NORTH MONTHLY OFF-PEAK - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.0643AZ",		"MISO IN. DAY-AHEAD PEAK - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.0643B3",		"MISO INDIANA HUB RT PEAK - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.0643BC",		"PJM N. IL HUB DA OFF-PK  - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.0643BE",		"PJM N. IL HUB DA PEAK - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.0643BF",		"ISO NE MASS HUB DA OFF-PK - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.0643BG",		"ISO NE MASS HUB DA PEAK - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.0643BM",		"CAISO NP-15 PEAK - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.0643BR",		"CAISO NP-15 OFF-PEAK - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.0643BS",		"PJM NI HUB RT OFF-PK - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.0643BT",		"PJM N. IL HUB RT PEAK - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.0643BW",		"NYISO ZONE J DA PEAK - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.0643BX",		"NYISO ZONE J DA OFF-PK - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.0643BY",		"NYISO ZONE A DA PEAK - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.0643BZ",		"NYISO ZONE A DA OFF-PK - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.0643C3",		"NYISO ZONE G DA PEAK - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.0643C4",		"NYISO ZONE G DA OFF-PK - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.0643CB",		"PALO VERDE DA PEAK - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.0643CJ",		"PJM BGE ZONE DAY AHEAD OFF PEAK MONTHLY - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.0643CK",		"PJM BGE ZONE DAY AHEAD: PEAK MONTHLY - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.0643CZ",		"PJM PECO ZONE DA PEAK - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.0643D1",		"PJM PECO ZONE OFF-PEAK MONTHLY - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.0643D7",		"PJM PPL ZONE DAY AHEAD: OFF-PEAK MONTHLY - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.0643D8",		"PJM PPL ZONE DA PEAK - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.0643DB",		"PJM WESTERN HUB DA OFF-PK - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.0643DC",		"PJM WESTERN HUB DA PEAK - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.0643DF",		"PJM WESTERN HUB RT PEAK MINI - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.0643DL",		"PJM PSEG DAY-AHEAD PEAK - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.0643DM",		"PJM PSEG ZONE DAY-AHEAD OFF-PEAK - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.0643IB",		"ERCOT N 345KV REAL T PK DALY M - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.0643ID",		"ERCOT N 345KV REAL T PK 2x16 - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.064AAA",		"ISONE..H.INTERNAL_HUB_month_on_dap - NODAL EXCHANGE"	},
				{	"COT.CmdtsFut.064AAB",		"ISONE..H.INTERNAL_HUB_month_off_dap - NODAL EXCHANGE"	},
				{	"COT.CmdtsFut.064BFI",		"MISO.INDIANA.HUB_month_on_dap - NODAL EXCHANGE"	},
				{	"COT.CmdtsFut.064BFJ",		"MISO.INDIANA.HUB_month_off_dap - NODAL EXCHANGE"	},
				{	"COT.CmdtsFut.064CXO",		"NYISO.HUD VL_month_on_dap - NODAL EXCHANGE"	},
				{	"COT.CmdtsFut.064CXP",		"NYISO.HUD VL_month_off_dap - NODAL EXCHANGE"	},
				{	"COT.CmdtsFut.064DEU",		"NYISO.WEST_month_on_dap - NODAL EXCHANGE"	},
				{	"COT.CmdtsFut.064DLW",		"PJM.AEP-DAYTON HUB_month_on_dap - NODAL EXCHANGE"	},
				{	"COT.CmdtsFut.064DLX",		"PJM.AEP-DAYTON HUB_month_off_dap - NODAL EXCHANGE"	},
				{	"COT.CmdtsFut.064DPQ",		"PJM.BGE_month_on_dap - NODAL EXCHANGE"	},
				{	"COT.CmdtsFut.064DPR",		"PJM.BGE_month_off_dap - NODAL EXCHANGE"	},
				{	"COT.CmdtsFut.064EJI",		"PJM.JCPL_month_on_dap - NODAL EXCHANGE"	},
				{	"COT.CmdtsFut.064EJJ",		"PJM.JCPL_month_off_dap - NODAL EXCHANGE"	},
				{	"COT.CmdtsFut.064ERM",		"PJM.N ILLINOIS HUB_month_on_dap - NODAL EXCHANGE"	},
				{	"COT.CmdtsFut.064ERN",		"PJM.N ILLINOIS HUB_month_off_dap - NODAL EXCHANGE"	},
				{	"COT.CmdtsFut.064EUY",		"PJM.PECO_month_on_dap - NODAL EXCHANGE"	},
				{	"COT.CmdtsFut.064EUZ",		"PJM.PECO_month_off_dap - NODAL EXCHANGE"	},
				{	"COT.CmdtsFut.064EVG",		"PJM.PEPCO_month_on_dap - NODAL EXCHANGE"	},
				{	"COT.CmdtsFut.064EVH",		"PJM.PEPCO_month_off_dap - NODAL EXCHANGE"	},
				{	"COT.CmdtsFut.064EWU",		"PJM.PPL_month_on_dap - NODAL EXCHANGE"	},
				{	"COT.CmdtsFut.064EWV",		"PJM.PPL_month_off_dap - NODAL EXCHANGE"	},
				{	"COT.CmdtsFut.064EXE",		"PJM.PSEG_month_on_dap - NODAL EXCHANGE"	},
				{	"COT.CmdtsFut.064EXF",		"PJM.PSEG_month_off_dap - NODAL EXCHANGE"	},
				{	"COT.CmdtsFut.064FHK",		"PJM.WESTERN HUB_month_on_dap - NODAL EXCHANGE"	},
				{	"COT.CmdtsFut.064FHL",		"PJM.WESTERN HUB_month_off_dap - NODAL EXCHANGE"	},
				{	"COT.CmdtsFut.064FKA",		"PJM.AEP-DAYTON HUB_month_on_rtp - NODAL EXCHANGE"	},
				{	"COT.CmdtsFut.064FKB",		"PJM.AEP-DAYTON HUB_month_off_rtp - NODAL EXCHANGE"	},
				{	"COT.CmdtsFut.064FKC",		"PJM.N ILLINOIS HUB_month_on_rtp - NODAL EXCHANGE"	},
				{	"COT.CmdtsFut.064FKD",		"PJM.N ILLINOIS HUB_month_off_rtp - NODAL EXCHANGE"	},
				{	"COT.CmdtsFut.064FKE",		"PJM.WESTERN HUB_month_on_rtp - NODAL EXCHANGE"	},
				{	"COT.CmdtsFut.064FKF",		"PJM.WESTERN HUB_month_off_rtp - NODAL EXCHANGE"	},
				{	"COT.CmdtsFut.064FZA",		"PJM.ATSI_month_on_dap - NODAL EXCHANGE"	},
				{	"COT.CmdtsFut.064FZB",		"PJM.ATSI_month_off_dap - NODAL EXCHANGE"	},
				{	"COT.CmdtsFut.064GAA",		"PJM.DEOK_month_on_dap - NODAL EXCHANGE"	},
				{	"COT.CmdtsFut.066411",		"ARGUS CIF ARA Lg Finl Propane - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.066413",		"ARGUS FAR EAST PROPANE - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.066416",		"ETHANE: MT. BELV-ENTERPRISE - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.06641A",		"NAT GASLNE OPIS MT B NONTET FP - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.06641D",		"BUTANE OPIS MT BELV NONTET FP  - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.06641F",		"PROPANE OPIS MT BELV NONTET FP - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.06641G",		"PROPANE OPIS MT BELVIEU TET FP - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.06641H",		"PROPANE ARGUS SAUDI CP FP - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.066652",		"EUROPEAN PROPANE CIF ARA - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.06665A",		"ARGUS PROPANE SAUDI ARAMCO - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.06665B",		"ARGUS PROPANE FAR EAST INDEX - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.06665G",		"PROPANE NON-LDH MT BEL - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.06665O",		"MT BELVIEU LDH PROPANE (OPIS) - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.06665P",		"MT BELVIEU ETHANE OPIS - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.06665Q",		"MT BELV NORM BUTANE OPIS - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.06665R",		"MT BELV NAT GASOLINE OPIS - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.06665T",		"CONWAY PROPANE (OPIS) - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.06665W",		"MT BELVIEU LDH PROPANE BALMO  - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.06665Z",		"MT BELVIEU NORMAL BUTANE BALMO - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.067411",		"CRUDE OIL: LIGHT SWEET-WTI - ICE FUTURES EUROPE"	},
				{	"COT.CmdtsFut.06741Q",		"WTI CRUDE OIL 1ST LINE - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.06741R",		"WTI 1st Line-Brent 1st Line - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.06742G",		"CRUDE DIFF-TMX WCS 1A INDEX - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.06742R",		"ARGUS MARS vs WTI TRADE MONTH - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.06742T",		"CRUDE DIFF-TMX SW 1A INDEX - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.06742U",		"ARGUS WTI Mid/WTI TRADE MONTH - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.067651",		"CRUDE OIL: LIGHT SWEET - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.06765A",		"WTI FINANCIAL CRUDE OIL - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.06765L",		"WTI-BRENT CALENDAR - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.06765T",		"BRENT CRUDE OIL LAST DAY - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.0676A5",		"WTI  HOUSTON ARGUS/WTI TR MO - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.067A71",		"WTI MIDLAND ARGUS VS WTI TRADE - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.067A75",		"WCS OIL NET ENERGY MONTHLY IND - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.073732",		"COCOA - ICE FUTURES U.S."	},
				{	"COT.CmdtsFut.075651",		"PALLADIUM - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.076651",		"PLATINUM - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.080732",		"SUGAR NO. 11 - ICE FUTURES U.S."	},
				{	"COT.CmdtsFut.083731",		"COFFEE C - ICE FUTURES U.S."	},
				{	"COT.CmdtsFut.084691",		"SILVER - COMMODITY EXCHANGE INC."	},
				{	"COT.CmdtsFut.085692",		"COPPER-GRADE #1 - COMMODITY EXCHANGE INC."	},
				{	"COT.CmdtsFut.088691",		"GOLD - COMMODITY EXCHANGE INC."	},
				{	"COT.CmdtsFut.111415",		"GASOLINE CRK-RBOB/BRENT 1st - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.111659",		"GASOLINE BLENDSTOCK (RBOB)  - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.11165K",		"RBOB CALENDAR - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.111A11",		"SINGAPORE MOGUS 92 - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.111A31",		"GULF COAST UNL 87 GAS M2 PL RB - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.111A34",		"GULF COAST CBOB GAS A2 PL RBOB - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.135731",		"CANOLA - ICE FUTURES U.S."	},
				{	"COT.CmdtsFut.191693",		"ALUMINUM MW US TR PLATTS - COMMODITY EXCHANGE INC."	},
				{	"COT.CmdtsFut.192651",		"HOT ROLLED COIL STEEL - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.261P05",		"NFX CS5TC CAPESIZE 5T/C AVG - NASDAQ FUTURES"	},
				{	"COT.CmdtsFut.261P07",		"NFX PM4TC PANAMAX 4T/C AVG - NASDAQ FUTURES"	},
				{	"COT.CmdtsFut.261P08",		"NFX SM10TC SUPRAMAX 10T/C AVG - NASDAQ FUTURES"	},
				{	"COT.CmdtsFut.261P09",		"NFX SM6TC SUPRAMAX 6T/C AVG - NASDAQ FUTURES"	},
				{	"COT.CmdtsFut.86465A",		"GULF JET NY HEAT OIL SPR - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.86465C",		"SING JET KERO GASOIL SPR - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.86565C",		"3.5% FUEL OIL RDAM CRACK SPR  - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.86665A",		"NAPHTHA CRACK SPR - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.86665E",		"MINI JAPAN C&F NAPHTHA - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.967654",		"EUROBOB OXY NWE CRK SPR  - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.005603",		"MINI SOYBEANS - CHICAGO BOARD OF TRADE"	},
				{	"COT.CmdtsFut.00639X",		"NJ SRECS VINTAGE 2018 - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.00639Y",		"CALIF CARBON ALL VINTAGE 2017 - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.0063AB",		"PJM TRI-RECs CLASS 1 Vin 2018 - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.0063AR",		"RGGI VINTAGE 2017 - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.02165B",		"NY RES FUEL 1.0% SULFUR SWAP - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.02165G",		"SING FUEL OIL 180 CAL SWAP - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.02165R",		"GULF 3% FUEL OIL BALMO SWAP - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.0233CS",		"TRANSCO STN 85 MONTHLY INDEX - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.0233DW",		"TETCO M2 Index (Receipts) - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.0233E5",		"TRANSCO LEIDY INDEX - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.023P01",		"HENRY HUB NAT GAS FINL-10000 - NASDAQ FUTURES"	},
				{	"COT.CmdtsFut.024658",		"COAL (API 4) FOB  RICH BAY FUT - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.03265C",		"JAPAN C&F NAPHTHA SWAP - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.0643A7",		"ERCOT NORTH 345K RT OFFPK DLY  - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.0643AP",		"NYISO ZONE C DA PEAK - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.0643CL",		"PJM RT PEAK CAL 1X - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.0643CM",		"PJM COMED ZONE DAY AHEAD LMP OFF-PEAK MONTHLY - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.0643CN",		"PJM COMED ZONE DAY AHEAD LMP PEAK MONTHLY - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.0643CU",		"PJM JCPL ZONE DAY-AHEAD PEAK  - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.0643D4",		"PJM PEPCO DA PEAK - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.0643D5",		"PJM PEPCO DAY-AHEAD OFF-PEAK - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.0643F2",		"PJM ATSI DA PEAK FIXED - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.0643F3",		"PJM ATSI DA OFFPEAK FIXED - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.064A58",		"PJM WESTERN PEAK REAL TIME - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.064HZR",		"MISO AMIL.BGS6 DAY-AHEAD PEAK  - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.111A41",		"RBOB GASOLINE/BRENT CRACK SPRD - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.195651",		"IRON ORE 62% FE-CFR CHINA TSI - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.86465K",		"JET UP-DOWN BALMO - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.86565A",		"GULF # 6 FUEL OIL CRACK SWAP - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.86565G",		"RTD 3.5% FUEL OIL CRK SPD SWP - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.86565N",		"GULF#6 FUELOIL BRENT CRACK SWP - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.00639H",		"CALIF CARBON ALL VINTAGE 2016 - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.00639W",		"NJ SRECS VINTAGE 2017 - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.0063A1",		"RGGI VINTAGE 2016 - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.0063AA",		"PJM TRI-RECs CLASS 1 Vin 2017 - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.021A19",		"MINI SING FUELOIL 180 CAL SWAP - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.02265J",		"SING GASOIL SWAP - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.025652",		"NEW YORK ETHANOL SWAP - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.0643B1",		"MISO INDIANA HUB RT PEAK MINI - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.0643B9",		"ISO NE MASS DA OFF-PK MINI - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.0643BA",		"ISO NE MASS DA PEAK MINI - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.0643C7",		"NYISO ZONE C DA OFF-PK - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.0643C8",		"NYISO ZONE F PEAK MONTHLY - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.0643CC",		"PALO VERDE DA OFF-PK - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.0643DK",		"PJM WESTERN HUB RT OFF-PK MINI - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.0643EA",		"AEP DAYTON REALTIME OFFPEAK-MI - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.0643F1",		"MISO IN. REALTIME OFFPEAK-MINI - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.064A59",		"PJM WESTERN HUB RT OFF 5 MW - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.064C74",		"NYISO ZONE A DAY AHEAD PEAK MI - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.064C75",		"NYISO ZONE A DAY AHEAD OFFPEAK - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.064C76",		"NYISO ZONE G DAY AHEAD PEAK MI - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.064C77",		"NYISO ZONE G DAY AHEAD OFFPEAK - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.064C78",		"NYISO ZONE J DAY AHEAD PEAK MI - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.064C79",		"NYISO ZONE J DAY AHEAD OFFPEAK - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.064C86",		"PJM AEP DAYTON REAL PEAK-MINI - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.064C87",		"PJM NI HUB REALTM OFFPEAK-MINI - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.064C88",		"PJM NI HUB REALTIME PEAK-MINI - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.067A49",		"CANADIAN HVY CRUDE NET ENRGY  - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.111A47",		"MINI EUROBOB GAS OXY NWE - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.86665B",		"JAPAN C&F NAPHTHA CRK SPR SWAP - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.002603",		"MINI CORN - CHICAGO BOARD OF TRADE"	},
				{	"COT.CmdtsFut.006261",		"SULFUR FINANCIAL INSTRUMENT - CHICAGO CLIMATE FUTURES EXCHANGE"	},
				{	"COT.CmdtsFut.006265",		"SULFUR FINANCIAL INSTR 2009 - CHICAGO CLIMATE FUTURES EXCHANGE"	},
				{	"COT.CmdtsFut.006268",		"CARBON FINANCIAL INSTRUMENT - CHICAGO CLIMATE FUTURES EXCHANGE"	},
				{	"COT.CmdtsFut.00626F",		"NITROGEN FIN INS ANNUAL 2009 - CHICAGO CLIMATE FUTURES EXCHANGE"	},
				{	"COT.CmdtsFut.00626U",		"RGGI CO2 ALLOWANCE 2009 - CHICAGO CLIMATE FUTURES EXCHANGE"	},
				{	"COT.CmdtsFut.006391",		"CALIF CARBON ALLOWANCE-2013 - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.006392",		"CALIFORNIA CARBON ALLOWANCE VINTAGE 2014 - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.006393",		"CALIFORNIA CARBON ALLOWANCE VINTAGE 2015 - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.00639U",		"RGGI VINTAGE 2014 - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.00639V",		"NJ SRECS VINTAGE 2016 - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.00639Z",		"RGGI VINTAGE 2015 - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.006GEC",		"IN DELIVERY MONTH EUA - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.02165C",		"EUR 1% FUEL OIL NWE CAL SWAP - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.02165H",		"FUEL OIL CARGOES B PLATTS SWAP - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.02165I",		"EAST WEST FUEL OIL SPR SWAP - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.02165J",		"SING 180 380 FUEL OIL SPR SWAP - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.02165L",		"3.5% FUEL OIL RDAM V. FOB MED - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.02165T",		"NY 1% V GULF 3% FUEL OIL SPR  - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.021A18",		"MINI EUR 3.5%FOIL RTD BALMOSWP - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.021A29",		"NY FO 1% v EUR 1% FO FOB NWE - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.02265T",		"SING GASOIL ICE GASOIL SWAP - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.02265U",		"NYMEX HEATING OIL/RDAM GASOIL - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.02265V",		"GASOIL (ICE) SWAP - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.022A05",		"GULF COAST ULSD SWAP - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.022A09",		"GULF COAST ULSD PLATT CRACK  - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.022A18",		"ULSD UP DOWN SWAP - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.022A22",		"SING GASOIL BALMO SWAP - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.022A24",		"GASOIL (ICE) MINI CAL SWAP - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.022A26",		"GASOIL 0.1 BARGE FOB RDM V ICE - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.022A60",		"GRP 3 ULSD VS HEATING OIL SPR - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.022A62",		"ULSD UP-DOWN BALMO SWAP - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.022A66",		"NY ULSD VS HEATING OIL SPR SWP - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.0233C1",		"SONAT - TIER 1 POOL (ZONE 0) - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.0233C9",		"TENNESSEE GAS PIPELINE CO. - ZONE L: 500 LEG POOL - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.0233CY",		"TRANSCONTINENTAL GAS PIPELINE CORP. - ZONE 6 (NY) - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.023655",		"E-MINI NATURAL GAS - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.02365A",		"MICHCON BASIS SWAP - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.02365B",		"PERMIAN BASIS SWAP - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.02365C",		"M-3 BASIS SWAP - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.02365D",		"TCO BASIS SWAP - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.02365E",		"MALIN BASIS SWAP - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.02365F",		"PG&E CITYGATE BASIS SWAP - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.02365G",		"NGPL TEXOK BASIS SWAP - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.02365J",		"SUMAS BASIS SWAP - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.02365K",		"NGPL MIDCON BASIS SWAP - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.02365L",		"DEMARC BASIS SWAP - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.02365M",		"VENTURA BASIS SWAP - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.02365N",		"DOMINION BASIS SWAP - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.02365O",		"WAHA BASIS SWAP - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.02365P",		"CIG ROCKIES BASIS SWAP - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.02365S",		"TRANSCO ZONE 3 BASIS SWAP - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.02365T",		"COLUMBIA GULF ONSHORE SWAP - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.023A09",		"HENRY HUB INDEX SWAP - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.023A10",		"HOUSTON SHIP CH INDEX SWAP - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.023A12",		"WAHA INDEX SWAP - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.023A23",		"SOCAL INDEX SWAP - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.023A26",		"TETCO M-3 INDEX SWAP - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.023A37",		"TRANSCO ZONE 4 BASIS SWAP - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.023A39",		"CENTERPOINT BASIS SWAP - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.023A85",		"COLUMBIA GULF ML SWAP - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.024651",		"CENTRAL APPALACHIAN COAL - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.024652",		"CSX COAL SWAP - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.024653",		"POWDER RIVER BASIN COAL SWAP - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.03265B",		"SING NAPHTHA SWAP - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.035650",		"ALBERTA BASIS SWAP - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.035651",		"CHICAGO BASIS SWAP - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.035652",		"HENRY HUB BASIS SWAP - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.035653",		"HOUSTON SHIP CH BASIS SWAP - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.035654",		"NW PIPE ROCKIES BASIS SWAP - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.035655",		"PANHANDLE BASIS SWAP - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.035656",		"SAN JUAN BASIS SWAP - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.035657",		"SOCAL BASIS SWAP - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.035658",		"TRANSCO ZONE 6 BASIS SWAP - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.056641",		"FRZN PORK BELLIES - CHICAGO MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.0643AF",		"NYISO ZONE F DA OFFPEAK - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.0643AT",		"ISO NEW ENGLAND CT DA LMP OFF-PEAK MONTHLY - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.0643AU",		"ISO NE CONN DA PEAK - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.0643CR",		"PJM EASTERN HUB DAY-AHEAD - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.0643CV",		"PJM JCPL ZONE DAY-AHEAD OFF-PEAK - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.064657",		"PJM WESTERN HUB RT PEAK 2.5MW - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.06465A",		"NYISO ZONE A LBMP SWAP - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.06465B",		"NYISO ZONE G LBMP SWAP - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.06465C",		"NYISO ZONE J LBMP SWAP - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.06465H",		"ISO NEW ENGLAND LMP SWAP - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.06465I",		"NORTH ILL CAL MONTH LMP OPT - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.06465K",		"AEP DAYTON PEAKCAL MONTH LMP 5 - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.06465M",		"PJM CAL MONTH OFF PK LMP SWAP - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.06465N",		"NORTH ILL OFF PK LMP SWAP - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.06465O",		"AEP DAYTON OFF PK LMP SWAP - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.06465P",		"NYISO ZONE A OFF PK LBMP SWAP - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.06465S",		"ISO NEW ENG OFF PK LMP SWAP - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.06465T",		"ISO NEW ENG CONN PEAK SWAP - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.064A01",		"CINERGY CAL MONTH LMP SWAP - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.064A02",		"CINERGY OFF PEAK LMP SWAP - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.064A34",		"PJM N ILL PEAK DAY AHEAD - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.064A35",		"PJM N ILL OFF PEAK DAY AHEAD - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.064A38",		"PJM AEP PEAK DAY AHEAD - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.064A39",		"PJM AEP OFF PEAK DAY AHEAD - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.064A42",		"PJM BGE PEAK DAY AHEAD - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.064A48",		"PJM JCPL PEAK DAY AHEAD - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.064A49",		"PJM JCPL OFF PEAK DAY AHEAD - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.064A50",		"PJM PEPCO PEAK DAY AHEAD - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.064A51",		"PJM PEPCO OFF PEAK DAY AHEAD - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.064A52",		"PJM PPL PEAK DAY AHEAD - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.064A53",		"PJM PPL OFF PEAK DAY AHEAD - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.064A54",		"PJM PSEG PEAK DAY AHEAD - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.064A55",		"PJM PSEG OFF PEAK DAY AHEAD - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.064A56",		"PJM WESTERN PEAK DAY AHEAD - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.064A57",		"PJM WESTERN OFF PEAK DAY AHEAD - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.064A60",		"ISO NEW ENG INT HUB PEAK SWAP - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.064A61",		"MW IND TR REAL TIME PEAK SWAP - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.064A62",		"MW IND TRANS PEAK SWAP - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.064A63",		"PJM N ILL HUB 5 MW PEAK SWAP - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.064A64",		"PJM AEP DAY HUB 5 MW PEAK SWAP - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.064A66",		"NYISO ZONE A 5 MW PEAK SWAP - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.064A68",		"NYISO ZONE G 5 MW PEAK - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.064A69",		"NYISO ZONE J 5 MW PEAK SWAP - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.064A71",		"ISO NEW ENG CONN OFF PEAK SWAP - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.064A78",		"ISO NEW ENG HUB OFF PEAK SWAP - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.064A79",		"PJM N ILL HUB 5 OFF PEAK SWAP - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.064A80",		"PJM AEP DAYTON OFF PEAK SWAP - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.064A82",		"NYISO ZONE A 5MW OFF PEAK SWAP - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.064A84",		"NYISO ZONE G 5 MW OFF PEAK - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.064A85",		"NYISO ZONE J5 MW OFF PEAK SWAP - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.064A87",		"MW CINRGY 5 OFF PEAK REAL-TIME - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.064A88",		"MW CINERGY OFF PEAK CAL MONTH - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.064C52",		"PJM WESTERN HUB REAL OFF DAY 5 - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.064EAS",		"PJM.EASTERN HUB_month_on_dap - NODAL EXCHANGE"	},
				{	"COT.CmdtsFut.064FJY",		"MISO.INDIANA.HUB_month_on_rtp - NODAL EXCHANGE"	},
				{	"COT.CmdtsFut.064IAN",		"ERCOT NORTH 345KV REAL-TIME PK - ICE FUTURES ENERGY DIV"	},
				{	"COT.CmdtsFut.066653",		"MT BELVIEU PROPANE SWAP - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.066654",		"MT BELVIEU NAT GASOLINE SWAP - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.066657",		"MT BELVIEU NORMAL BUTANE SWAP - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.066A19",		"MT BELV NORM BUT LDH OPIS SWP - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.067655",		"E-MINI CRUDE OIL: LIGHT SWEET - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.06765G",		"DUBAI CRUDE OIL CALENDAR SWAP - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.06765I",		"WTI CRUDE OIL FINANCIAL - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.06765J",		"BRENT FINANCIAL - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.06765M",		"DATED TO FRONTLINE BRENT SWAP - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.06765N",		"BRENT (ICE) CALENDAR SWAP - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.06765O",		"BRENT-DUBAI SWAP - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.067DU1",		"OMAN CRUDE OIL - DUBAI MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.11165J",		"RBOB GASOLINE FINANCIAL - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.11165L",		"RBOB UP-DOWN CAL - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.16164H",		"CHICAGO HDD - CHICAGO MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.16264C",		"NEW YORK CDD - CHICAGO MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.16264H",		"NEW YORK HDD - CHICAGO MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.26265A",		"GULF COAST JET FUEL CAL SWAP - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.26265D",		"SING JET KERO SWAP - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.86465D",		"JET CIF NWE/GASOIL FUT - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.86565D",		"1% FUEL OIL NWE CRACK SPR - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.86665G",		"MINI EUROPE NAPHTHA BALMO SWAP - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.86765C",		"GASOIL CRACK SPR SWAP - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.869652",		"FAM BIODIESEL V GASOIL SPR SWP - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.869654",		"FAME BIODIESEL V GASOIL SPR SP - NEW YORK MERCANTILE EXCHANGE"	},
				{	"COT.CmdtsFut.967652",		"RBOB CRACK SPREAD SWAP - NEW YORK MERCANTILE EXCHANGE"	}


			};
			
			return values[(int)cotId,0];
		}
		
		DMFXClient _dmfxClient = null; // DMFX connection client
		string _country = "US"; // US by default
		string _ticker = null; // ticker to display
		/*
		private System.Drawing.KnownColor[] Colors = {KnownColor.Red, KnownColor.Green, KnownColor.Blue, KnownColor.Orange, KnownColor.Purple};
		*/
		
		
		protected override void OnStateChange()
		{

				if (State == State.SetDefaults)
				{
					Description									= @"DarkMindFX - COT indicator for Financials - Futures Only Net Positions";
					Name										= "DMFX - COT: Commodities - Futures Only";
					Calculate									= Calculate.OnBarClose;
					IsOverlay									= false;
					DisplayInDataBox							= true;
					DrawOnPricePanel							= false;
					DrawHorizontalGridLines						= true;
					DrawVerticalGridLines						= true;
					PaintPriceMarkers							= true;
					ScaleJustification							= NinjaTrader.Gui.Chart.ScaleJustification.Right;
					//Disable this property if your indicator requires custom values that cumulate with each new market data event. 
					//See Help Guide for additional information.
					IsSuspendedWhileInactive					= true;

                    Host = "http://darkmindfx.com/";
                    AccountKey = "[Your Account Key]"; ;
					COTCode = ECOTCmdtsCodes.CRUDE_OIL__LIGHT_SWEET_WTI___ICE_FUTURES_EUROPE_;
					WeeksBack = 500;
					
					AddPlot(Brushes.Aqua, "Open_Interest_All");
					AddPlot(Brushes.Green, "Prod_Merc_Positions_Long_All");
					AddPlot(Brushes.Red, "Prod_Merc_Positions_Short_All");
					AddPlot(Brushes.GreenYellow, "Swap_Positions_Long_All");
					AddPlot(Brushes.Orange, "Swap_Positions_Short_All");
					AddPlot(Brushes.Blue, "M_Money_Positions_Long_All");
					AddPlot(Brushes.BlueViolet, "M_Money_Positions_Short_All");
					AddPlot(Brushes.AliceBlue, "Other_Rept_Positions_Long_All");
					AddPlot(Brushes.Coral, "Other_Rept_Positions_Short_All");
				}
				else if (State == State.Configure)
				{
					
					if(_dmfxClient == null)
					{
						_dmfxClient = new DMFXClient();
					}
					
					_ticker = GetTicker(COTCode);
					EErrorCodes result = _dmfxClient.InitSession(Host, AccountKey);	
					if(result == EErrorCodes.Success)
					{
						Print("Session opened for " + AccountKey);
						
						result = _dmfxClient.GetTimeSeriesInfo(_country, _ticker);
						if(result == EErrorCodes.Success)
						{
							DateTime periodStart = DateTime.UtcNow - TimeSpan.FromDays(Math.Max(WeeksBack, 52) * 7);
							DateTime periodEnd = DateTime.UtcNow;
							result = _dmfxClient.GetTimeSeries(_country, _ticker, ETimeFrame.Weekly, periodStart, periodEnd);
							if(result != EErrorCodes.Success)
							{
								Print("GetTimeSeries failed: " + result + " - " + _dmfxClient.GetLastError());
							}
							else
							{
								Print("Data loaded for " + _ticker);
							}
						}
						else
						{
							Print("GetTimeSeriesInfo failed: " + result + " - " + _dmfxClient.GetLastError());
						}
					}
					else
					{
						Print("InitSession failed: " + result + " - " + _dmfxClient.GetLastError());
					}
				}
				else if(State == State.Terminated)
				{
					if(_dmfxClient != null)
					{
						EErrorCodes result = _dmfxClient.CloseSession();
						Print("Session closed for " + AccountKey);
					}
				}
			
		}

		protected override void OnBarUpdate()
		{
			
			if(_dmfxClient != null)
			{
				IList<string> columns = _dmfxClient.GetColumns(_ticker);
				if(columns != null)
				{
					DateTime dtNow = Time[0];

					for(int i = 0; i < columns.Count; ++i)
					{
						decimal value = _dmfxClient.GetDateValue(_ticker, columns[i], dtNow);
						Values[i][0] = (double)value;
					}
				}
			}
			
		}		
		
		
		[NinjaScriptProperty]
		[Display(ResourceType = typeof(Custom.Resource), Name = "AccountKey", GroupName = "NinjaScriptParameters", Order = 0)]
		public string AccountKey
		{ get; set; }
		
		[NinjaScriptProperty]
		[Display(ResourceType = typeof(Custom.Resource), Name = "COTCode", GroupName = "NinjaScriptParameters", Order = 1)]
		public NinjaTrader.NinjaScript.Indicators.DMFXCOTCmdtsFut.ECOTCmdtsCodes COTCode
		{ get; set; }
		
		[NinjaScriptProperty]
		[Display(ResourceType = typeof(Custom.Resource), Name = "WeeksBack", GroupName = "NinjaScriptParameters", Order = 2)]
		public int WeeksBack
		{ get; set; }
		
		[NinjaScriptProperty]
		[Display(ResourceType = typeof(Custom.Resource), Name = "Host", GroupName = "NinjaScriptParameters", Order = 3)]
		public string Host
		{ get; set; }
	}
}

#region NinjaScript generated code. Neither change nor remove.

namespace NinjaTrader.NinjaScript.Indicators
{
	public partial class Indicator : NinjaTrader.Gui.NinjaScript.IndicatorRenderBase
	{
		private DMFXCOTCmdtsFut[] cacheDMFXCOTCmdtsFut;
		public DMFXCOTCmdtsFut DMFXCOTCmdtsFut(string accountKey, NinjaTrader.NinjaScript.Indicators.DMFXCOTCmdtsFut.ECOTCmdtsCodes cOTCode, int weeksBack, string host)
		{
			return DMFXCOTCmdtsFut(Input, accountKey, cOTCode, weeksBack, host);
		}

		public DMFXCOTCmdtsFut DMFXCOTCmdtsFut(ISeries<double> input, string accountKey, NinjaTrader.NinjaScript.Indicators.DMFXCOTCmdtsFut.ECOTCmdtsCodes cOTCode, int weeksBack, string host)
		{
			if (cacheDMFXCOTCmdtsFut != null)
				for (int idx = 0; idx < cacheDMFXCOTCmdtsFut.Length; idx++)
					if (cacheDMFXCOTCmdtsFut[idx] != null && cacheDMFXCOTCmdtsFut[idx].AccountKey == accountKey && cacheDMFXCOTCmdtsFut[idx].COTCode == cOTCode && cacheDMFXCOTCmdtsFut[idx].WeeksBack == weeksBack && cacheDMFXCOTCmdtsFut[idx].Host == host && cacheDMFXCOTCmdtsFut[idx].EqualsInput(input))
						return cacheDMFXCOTCmdtsFut[idx];
			return CacheIndicator<DMFXCOTCmdtsFut>(new DMFXCOTCmdtsFut(){ AccountKey = accountKey, COTCode = cOTCode, WeeksBack = weeksBack, Host = host }, input, ref cacheDMFXCOTCmdtsFut);
		}
	}
}

namespace NinjaTrader.NinjaScript.MarketAnalyzerColumns
{
	public partial class MarketAnalyzerColumn : MarketAnalyzerColumnBase
	{
		public Indicators.DMFXCOTCmdtsFut DMFXCOTCmdtsFut(string accountKey, NinjaTrader.NinjaScript.Indicators.DMFXCOTCmdtsFut.ECOTCmdtsCodes cOTCode, int weeksBack, string host)
		{
			return indicator.DMFXCOTCmdtsFut(Input, accountKey, cOTCode, weeksBack, host);
		}

		public Indicators.DMFXCOTCmdtsFut DMFXCOTCmdtsFut(ISeries<double> input , string accountKey, NinjaTrader.NinjaScript.Indicators.DMFXCOTCmdtsFut.ECOTCmdtsCodes cOTCode, int weeksBack, string host)
		{
			return indicator.DMFXCOTCmdtsFut(input, accountKey, cOTCode, weeksBack, host);
		}
	}
}

namespace NinjaTrader.NinjaScript.Strategies
{
	public partial class Strategy : NinjaTrader.Gui.NinjaScript.StrategyRenderBase
	{
		public Indicators.DMFXCOTCmdtsFut DMFXCOTCmdtsFut(string accountKey, NinjaTrader.NinjaScript.Indicators.DMFXCOTCmdtsFut.ECOTCmdtsCodes cOTCode, int weeksBack, string host)
		{
			return indicator.DMFXCOTCmdtsFut(Input, accountKey, cOTCode, weeksBack, host);
		}

		public Indicators.DMFXCOTCmdtsFut DMFXCOTCmdtsFut(ISeries<double> input , string accountKey, NinjaTrader.NinjaScript.Indicators.DMFXCOTCmdtsFut.ECOTCmdtsCodes cOTCode, int weeksBack, string host)
		{
			return indicator.DMFXCOTCmdtsFut(input, accountKey, cOTCode, weeksBack, host);
		}
	}
}

#endregion
